import type { TourDefinition } from '../../schema.js';
import { PERMISSIONS } from '../../../../constants/permissions.js';

// Deep-dive companion to `purchase-returns-overview`. Grounded against PurchaseReturnService.ts
// (apps/purchase-service) and the accounting/GST consumer audit. Key finding, and the reason this
// guide exists: approving a Purchase Return correctly deducts stock and reduces the supplier
// balance, but there is currently no accounting consumer for PURCHASE_RETURN_APPROVED anywhere in
// accounting-service — no journal entry is ever posted for it. The GST-side consumer does exist,
// but the payload it's sent is missing the tax fields, so the ITC-reversal ledger entry is
// recorded with taxable/cgst/sgst/igst all at zero. This means GSTR-3B's Net ITC (purchases minus
// purchase returns) never actually subtracts anything for a return today. Stated here as a known
// limitation to plan around, not as something broken to "work around" — do not describe it as
// working in any tour copy.
const tour: TourDefinition = {
  id: 'purchase-returns-complete-guide',
  version: 1,
  type: 'complete',
  title: 'Purchase Returns — complete guide',
  description:
    "The Draft→Approve flow, what Approve actually updates, and a real gap to know about: returns don't yet post to your books or correctly reverse GST input credit.",
  module: 'purchase',
  estimatedMinutes: 6,
  requiredPermissions: [PERMISSIONS.PURCHASE_RETURN_VIEW],
  steps: [
    {
      id: 'purpose',
      route: 'purchase/returns',
      title: 'Why this page exists',
      body: 'Send goods back to a supplier against a specific GRN — damaged on arrival, wrong item, quality issue, or simply excess quantity.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.PURCHASE_RETURN_VIEW,
    },
    {
      id: 'create',
      route: 'purchase/returns/new',
      title: 'Creating a return',
      body: "Enter the source GRN's ID and Load GRN — there's no search, so find the ID on the GRN list first. Pick a return quantity per line (capped by what was received, though only as a soft input hint) and a reason.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.PURCHASE_RETURN_VIEW,
    },
    {
      id: 'draft-stage',
      route: 'purchase/returns',
      title: 'This has a Draft stage — unlike a Sale Return',
      body: "If you're used to Sale Returns (which apply immediately), note the difference here: creating a Purchase Return only saves a Draft. Nothing moves until you separately Approve it.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.PURCHASE_RETURN_VIEW,
    },
    {
      id: 'approve',
      route: 'purchase/returns',
      target: '[data-tour-id="purchase-return-approve-row-action"]',
      title: 'Approve',
      body: "You'll be asked to confirm — this deducts the returned quantity from stock, reduces the supplier's balance, and auto-generates a debit note. It cannot be undone.",
      placement: 'bottom',
      mode: 'informational',
      requiredPermission: PERMISSIONS.PURCHASE_RETURN_VIEW,
    },
    {
      id: 'debit-notes',
      route: 'purchase/returns',
      title: 'Debit Notes tab',
      body: "A read-only list of debit notes generated by approved returns. There's no way to mark one Issued, Adjusted, or Refunded from here, and no link back to the return that created it.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.PURCHASE_RETURN_VIEW,
    },
    {
      id: 'business-impact',
      route: 'purchase/returns',
      title: 'What Approve actually touches',
      body: 'Inventory and the supplier balance are current. Your books and GST return are not — yet.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.PURCHASE_RETURN_VIEW,
      calloutTitle: 'Business impact',
      calloutVariant: 'info',
      businessImpact: [
        'Inventory: stock is deducted immediately and correctly on Approve.',
        'Supplier balance: reduced immediately by the return amount — accurate and up to date.',
        'Accounting: no journal entry is posted for a Purchase Return today. It will not appear in your General Ledger even though stock and supplier balance both reflect it.',
        "GST: an ITC-reversal entry is written, but currently with the taxable and tax amounts recorded as zero — so the GST module's Net ITC figure does not actually decrease from a return yet.",
      ],
    },
    {
      id: 'common-mistakes',
      route: 'purchase/returns',
      title: 'Common mistakes',
      body: "Don't assume the books reconcile automatically here.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.PURCHASE_RETURN_VIEW,
      calloutTitle: 'Common mistakes',
      calloutVariant: 'warning',
      businessImpact: [
        "Assuming a Trial Balance or GSTR-3B check will show the return automatically — it won't, until the accounting and GST posting gaps above are fixed. Track return-driven ITC reversal manually for now.",
        "Approving without double-checking the return quantity — the input's max is a soft hint, not an enforced limit.",
        "Looking for a debit note's originating return — there's no link; keep your own record if you need to trace one back.",
      ],
    },
    {
      id: 'best-practices',
      route: 'purchase/returns',
      title: 'Best practices',
      body: "Compensate for the known gaps until they're closed.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.PURCHASE_RETURN_VIEW,
      calloutTitle: 'Best practices',
      calloutVariant: 'success',
      businessImpact: [
        'Post a manual accounting adjustment for any material purchase return until an automatic journal entry ships.',
        "Manually reduce your claimed ITC for any GST-bearing return when filing GSTR-3B — the system won't do it for you yet.",
        "Pick a specific, accurate reason at creation — it's the only record of why the return happened, since there's no detail page to add context later.",
      ],
    },
  ],
};

export default tour;
