stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  GIT_STRATEGY: clone
  GIT_CLEAN_FLAGS: -ffdx

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "Creating env files before build"
    - |
      cat > sale-erp-backend/.env <<EOF
      PORT=$PORT
      SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
      SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
      SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      CORS_ALLOWED_ORIGIN_PATTERNS=$CORS_ALLOWED_ORIGIN_PATTERNS
      JWT_SECRET=$JWT_SECRET
      JWT_EXPIRATION=$JWT_EXPIRATION
      JWT_REFRESH_EXPIRATION=$JWT_REFRESH_EXPIRATION
      MAX_FILE_SIZE=$MAX_FILE_SIZE
      MAX_REQUEST_SIZE=$MAX_REQUEST_SIZE
      AWS_S3_BUCKET=$AWS_S3_BUCKET
      AWS_REGION=$AWS_REGION
      AWS_S3_PUBLIC_URL=$AWS_S3_PUBLIC_URL
      AWS_S3_MAX_IMAGE_SIZE=$AWS_S3_MAX_IMAGE_SIZE
      AWS_S3_ALLOWED_CONTENT_TYPES=$AWS_S3_ALLOWED_CONTENT_TYPES
      APP_LOG_LEVEL=$APP_LOG_LEVEL
      EOF
    - |
      cat > sale-erp-froentend/.env <<EOF
      VITE_API_BASE_URL=$VITE_API_BASE_URL
      EOF

deploy:
  stage: deploy
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
  script:
    - |
      ssh $EC2_USER@$EC2_HOST "
      cd ~/sales-erp-app &&
      echo 'Pulling latest code' &&
      git fetch origin &&
      git reset --hard origin/main &&

      echo 'Creating root env file' &&
      cat > .env <<EOF
      VITE_API_BASE_URL=$VITE_API_BASE_URL
      EOF

      echo 'Creating backend env file' &&
      cat > sale-erp-backend/.env <<EOF
      PORT=$PORT
      SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
      SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
      SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      CORS_ALLOWED_ORIGIN_PATTERNS=$CORS_ALLOWED_ORIGIN_PATTERNS
      JWT_SECRET=$JWT_SECRET
      JWT_EXPIRATION=$JWT_EXPIRATION
      JWT_REFRESH_EXPIRATION=$JWT_REFRESH_EXPIRATION
      MAX_FILE_SIZE=$MAX_FILE_SIZE
      MAX_REQUEST_SIZE=$MAX_REQUEST_SIZE
      AWS_S3_BUCKET=$AWS_S3_BUCKET
      AWS_REGION=$AWS_REGION
      AWS_S3_PUBLIC_URL=$AWS_S3_PUBLIC_URL
      AWS_S3_MAX_IMAGE_SIZE=$AWS_S3_MAX_IMAGE_SIZE
      AWS_S3_ALLOWED_CONTENT_TYPES=$AWS_S3_ALLOWED_CONTENT_TYPES
      APP_LOG_LEVEL=$APP_LOG_LEVEL
      EOF

      echo 'Creating frontend env file' &&
      cat > sale-erp-froentend/.env <<EOF
      VITE_API_BASE_URL=$VITE_API_BASE_URL
      EOF

      echo 'Stopping containers' &&
      docker-compose down || true &&

      echo 'Building fresh images' &&
      docker-compose build --no-cache &&

      echo 'Starting containers' &&
      docker-compose up -d &&

      echo 'Cleaning unused images' &&
      docker image prune -f
      "
  
