module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-case': [2, 'always', 'kebab-case'],
    'scope-enum': [
      2,
      'always',
      [
        'sales',
        'inventory',
        'accounting',
        'purchase',
        'hr',
        'gst',
        'notification',
        'scheduler',
        'search',
        'report',
        'auth',
        'tenant',
        'api-gateway',
        'platform-sdk',
        'shared-types',
        'shared-utils',
        'db-client',
        'cache-client',
        'event-bus-client',
        'logger',
        'config',
        'web-frontend',
        'pos-frontend',
        'infra',
        'ci',
        'deps',
        'release',
      ],
    ],
  },
};
