// HSN seed data — top textile/retail chapters for Indian cloth retail
// Source: CBIC HSN Master (selected textile + retail chapters)

export interface HsnSeedRow {
  hsnCode: string;
  description: string;
  gstRate: string;
  cessRate: string;
  chapter: string;
  heading: string;
}

export const HSN_SEED_DATA: HsnSeedRow[] = [
  // Chapter 50 — Silk
  {
    hsnCode: '5007',
    description: 'Woven fabrics of silk or silk waste',
    gstRate: '5',
    cessRate: '0',
    chapter: '50',
    heading: '5007',
  },
  {
    hsnCode: '500710',
    description: 'Fabrics of noil silk',
    gstRate: '5',
    cessRate: '0',
    chapter: '50',
    heading: '5007',
  },
  {
    hsnCode: '500720',
    description: 'Other woven fabrics, 85%+ silk or silk waste',
    gstRate: '5',
    cessRate: '0',
    chapter: '50',
    heading: '5007',
  },
  {
    hsnCode: '500790',
    description: 'Other woven fabrics of silk',
    gstRate: '5',
    cessRate: '0',
    chapter: '50',
    heading: '5007',
  },

  // Chapter 52 — Cotton
  {
    hsnCode: '5208',
    description: 'Woven fabrics of cotton, 85%+, weight ≤ 200 g/m²',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5208',
  },
  {
    hsnCode: '520811',
    description: 'Plain weave cotton, 85%+, wt ≤ 100g/m² (unbleached)',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5208',
  },
  {
    hsnCode: '520812',
    description: 'Plain weave cotton, 85%+, wt 100-200g/m² (unbleached)',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5208',
  },
  {
    hsnCode: '520821',
    description: 'Plain weave cotton, 85%+, wt ≤ 100g/m² (bleached)',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5208',
  },
  {
    hsnCode: '520831',
    description: 'Plain weave cotton dyed, 85%+, wt ≤ 100g/m²',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5208',
  },
  {
    hsnCode: '520851',
    description: 'Plain weave cotton printed, 85%+, wt ≤ 100g/m²',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5208',
  },
  {
    hsnCode: '5209',
    description: 'Woven fabrics of cotton, 85%+, weight > 200 g/m²',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5209',
  },
  {
    hsnCode: '5210',
    description: 'Woven fabrics of cotton, < 85%, mixed mainly with MMF',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5210',
  },
  {
    hsnCode: '5211',
    description: 'Woven fabrics of cotton, < 85%, mixed mainly with MMF, wt > 200g',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5211',
  },
  {
    hsnCode: '5212',
    description: 'Other woven fabrics of cotton',
    gstRate: '5',
    cessRate: '0',
    chapter: '52',
    heading: '5212',
  },

  // Chapter 54 — Man-made filaments
  {
    hsnCode: '5407',
    description: 'Woven fabrics of synthetic filament yarn',
    gstRate: '5',
    cessRate: '0',
    chapter: '54',
    heading: '5407',
  },
  {
    hsnCode: '540710',
    description: 'Woven fabrics of high tenacity yarn of nylon/polyamide',
    gstRate: '5',
    cessRate: '0',
    chapter: '54',
    heading: '5407',
  },
  {
    hsnCode: '540720',
    description: 'Woven fabrics obtained from strip/the like of synthetic fibre',
    gstRate: '5',
    cessRate: '0',
    chapter: '54',
    heading: '5407',
  },
  {
    hsnCode: '540761',
    description: 'Woven fabrics, unbleached or bleached, 85%+ polyester filaments',
    gstRate: '5',
    cessRate: '0',
    chapter: '54',
    heading: '5407',
  },
  {
    hsnCode: '540771',
    description: 'Woven fabrics, unbleached or bleached, 85%+ polyester staple',
    gstRate: '5',
    cessRate: '0',
    chapter: '54',
    heading: '5407',
  },
  {
    hsnCode: '5408',
    description: 'Woven fabrics of artificial filament yarn',
    gstRate: '5',
    cessRate: '0',
    chapter: '54',
    heading: '5408',
  },

  // Chapter 55 — Man-made staple fibres
  {
    hsnCode: '5512',
    description: 'Woven fabrics of synthetic staple fibres, 85%+',
    gstRate: '5',
    cessRate: '0',
    chapter: '55',
    heading: '5512',
  },
  {
    hsnCode: '5513',
    description: 'Woven fabrics of synthetic staple fibres, < 85%, mixed mainly with cotton',
    gstRate: '5',
    cessRate: '0',
    chapter: '55',
    heading: '5513',
  },
  {
    hsnCode: '5514',
    description: 'Woven fabrics of synthetic staple fibres, < 85%, weight > 170g/m²',
    gstRate: '5',
    cessRate: '0',
    chapter: '55',
    heading: '5514',
  },
  {
    hsnCode: '5515',
    description: 'Other woven fabrics of synthetic staple fibres',
    gstRate: '5',
    cessRate: '0',
    chapter: '55',
    heading: '5515',
  },
  {
    hsnCode: '5516',
    description: 'Woven fabrics of artificial staple fibres',
    gstRate: '5',
    cessRate: '0',
    chapter: '55',
    heading: '5516',
  },

  // Chapter 58 — Special woven fabrics
  {
    hsnCode: '5801',
    description: 'Woven pile fabrics and chenille fabrics (excl. terry towelling)',
    gstRate: '5',
    cessRate: '0',
    chapter: '58',
    heading: '5801',
  },
  {
    hsnCode: '5804',
    description: 'Tulles, lace, net, embroidery',
    gstRate: '12',
    cessRate: '0',
    chapter: '58',
    heading: '5804',
  },
  {
    hsnCode: '5806',
    description: 'Narrow woven fabrics, ribbons',
    gstRate: '12',
    cessRate: '0',
    chapter: '58',
    heading: '5806',
  },
  {
    hsnCode: '5810',
    description: 'Embroidery in piece, in strips or in motifs',
    gstRate: '12',
    cessRate: '0',
    chapter: '58',
    heading: '5810',
  },

  // Chapter 61 — Knitted or crocheted garments
  {
    hsnCode: '6101',
    description: "Men's/boys' overcoats, car-coats etc., knitted",
    gstRate: '5',
    cessRate: '0',
    chapter: '61',
    heading: '6101',
  },
  {
    hsnCode: '6104',
    description: "Women's suits, ensembles, jackets etc., knitted",
    gstRate: '5',
    cessRate: '0',
    chapter: '61',
    heading: '6104',
  },
  {
    hsnCode: '6105',
    description: "Men's/boys' shirts, knitted",
    gstRate: '5',
    cessRate: '0',
    chapter: '61',
    heading: '6105',
  },
  {
    hsnCode: '6109',
    description: 'T-shirts, singlets and other vests, knitted',
    gstRate: '5',
    cessRate: '0',
    chapter: '61',
    heading: '6109',
  },
  {
    hsnCode: '6110',
    description: 'Jerseys, pullovers, sweatshirts, waistcoats, similar articles, knitted',
    gstRate: '5',
    cessRate: '0',
    chapter: '61',
    heading: '6110',
  },
  {
    hsnCode: '6115',
    description: 'Pantyhose, tights, stockings, socks and other hosiery',
    gstRate: '5',
    cessRate: '0',
    chapter: '61',
    heading: '6115',
  },

  // Chapter 62 — Woven garments
  {
    hsnCode: '6201',
    description: "Men's/boys' overcoats, car-coats, cloaks, anoraks etc.",
    gstRate: '12',
    cessRate: '0',
    chapter: '62',
    heading: '6201',
  },
  {
    hsnCode: '6203',
    description: "Men's/boys' suits, ensembles, jackets, blazers, trousers",
    gstRate: '12',
    cessRate: '0',
    chapter: '62',
    heading: '6203',
  },
  {
    hsnCode: '6204',
    description: "Women's/girls' suits, ensembles, jackets, dresses, skirts",
    gstRate: '12',
    cessRate: '0',
    chapter: '62',
    heading: '6204',
  },
  {
    hsnCode: '6205',
    description: "Men's/boys' shirts",
    gstRate: '12',
    cessRate: '0',
    chapter: '62',
    heading: '6205',
  },
  {
    hsnCode: '6206',
    description: "Women's/girls' blouses, shirts",
    gstRate: '12',
    cessRate: '0',
    chapter: '62',
    heading: '6206',
  },
  {
    hsnCode: '6210',
    description: 'Garments made up of fabrics of heading 5602, 5603, 5903 etc.',
    gstRate: '12',
    cessRate: '0',
    chapter: '62',
    heading: '6210',
  },
  {
    hsnCode: '6211',
    description: 'Track suits, ski suits and swimwear',
    gstRate: '12',
    cessRate: '0',
    chapter: '62',
    heading: '6211',
  },
  {
    hsnCode: '6217',
    description: 'Other made up clothing accessories; parts of garments',
    gstRate: '12',
    cessRate: '0',
    chapter: '62',
    heading: '6217',
  },

  // Retail / accessories
  {
    hsnCode: '6301',
    description: 'Blankets and travelling rugs',
    gstRate: '12',
    cessRate: '0',
    chapter: '63',
    heading: '6301',
  },
  {
    hsnCode: '6302',
    description: 'Bed linen, table linen, toilet linen and kitchen linen',
    gstRate: '5',
    cessRate: '0',
    chapter: '63',
    heading: '6302',
  },
  {
    hsnCode: '6303',
    description: 'Curtains, drapes and interior blinds; curtain or bed valances',
    gstRate: '5',
    cessRate: '0',
    chapter: '63',
    heading: '6303',
  },
  {
    hsnCode: '6305',
    description: 'Sacks and bags for packing of goods',
    gstRate: '12',
    cessRate: '0',
    chapter: '63',
    heading: '6305',
  },

  // Common retail items
  {
    hsnCode: '9404',
    description: 'Mattresses, quilts, pillows, sleeping bags',
    gstRate: '18',
    cessRate: '0',
    chapter: '94',
    heading: '9404',
  },

  // Tailoring / alteration charges (service)
  {
    hsnCode: '998815',
    description: 'Tailoring services — SAC code for tailoring/garment stitching',
    gstRate: '5',
    cessRate: '0',
    chapter: '99',
    heading: '9988',
  },

  // Multi-vertical platform audit 2026-08-16, Phase 2: grocery/FMCG chapters. hsnMaster is a
  // global (not tenant-scoped) reference table seeded unconditionally on every gst-service
  // boot — additive rows here don't touch or affect any existing textile row.
  // Chapter 04 — Dairy
  {
    hsnCode: '0401',
    description: 'Milk and cream, not concentrated/sweetened',
    gstRate: '0',
    cessRate: '0',
    chapter: '04',
    heading: '0401',
  },
  {
    hsnCode: '0402',
    description: 'Milk and cream, concentrated or containing added sugar (milk powder)',
    gstRate: '5',
    cessRate: '0',
    chapter: '04',
    heading: '0402',
  },
  {
    hsnCode: '0405',
    description: 'Butter and other fats and oils derived from milk; ghee',
    gstRate: '12',
    cessRate: '0',
    chapter: '04',
    heading: '0405',
  },
  {
    hsnCode: '0406',
    description: 'Cheese and curd',
    gstRate: '12',
    cessRate: '0',
    chapter: '04',
    heading: '0406',
  },
  // Chapter 07/08 — Vegetables and fruit (fresh, unprocessed)
  {
    hsnCode: '0701',
    description: 'Potatoes, fresh or chilled',
    gstRate: '0',
    cessRate: '0',
    chapter: '07',
    heading: '0701',
  },
  {
    hsnCode: '0702',
    description: 'Tomatoes, fresh or chilled',
    gstRate: '0',
    cessRate: '0',
    chapter: '07',
    heading: '0702',
  },
  {
    hsnCode: '0803',
    description: 'Bananas, fresh or dried',
    gstRate: '0',
    cessRate: '0',
    chapter: '08',
    heading: '0803',
  },
  // Chapter 09 — Coffee, tea, spices
  {
    hsnCode: '0901',
    description: 'Coffee, whether or not roasted or decaffeinated',
    gstRate: '5',
    cessRate: '0',
    chapter: '09',
    heading: '0901',
  },
  {
    hsnCode: '0902',
    description: 'Tea, whether or not flavoured',
    gstRate: '5',
    cessRate: '0',
    chapter: '09',
    heading: '0902',
  },
  {
    hsnCode: '0904',
    description: 'Pepper; dried/crushed/ground fruits of genus Capsicum',
    gstRate: '5',
    cessRate: '0',
    chapter: '09',
    heading: '0904',
  },
  {
    hsnCode: '0910',
    description: 'Ginger, saffron, turmeric, thyme, curry and other spices',
    gstRate: '5',
    cessRate: '0',
    chapter: '09',
    heading: '0910',
  },
  // Chapter 10/11 — Cereals and milling products (staples)
  {
    hsnCode: '1001',
    description: 'Wheat and meslin',
    gstRate: '0',
    cessRate: '0',
    chapter: '10',
    heading: '1001',
  },
  {
    hsnCode: '1006',
    description: 'Rice',
    gstRate: '0',
    cessRate: '0',
    chapter: '10',
    heading: '1006',
  },
  {
    hsnCode: '1101',
    description: 'Wheat or meslin flour (atta)',
    gstRate: '0',
    cessRate: '0',
    chapter: '11',
    heading: '1101',
  },
  // Chapter 15 — Edible oils
  {
    hsnCode: '1509',
    description: 'Olive oil and its fractions',
    gstRate: '5',
    cessRate: '0',
    chapter: '15',
    heading: '1509',
  },
  {
    hsnCode: '1512',
    description: 'Sunflower-seed, safflower or cotton-seed oil',
    gstRate: '5',
    cessRate: '0',
    chapter: '15',
    heading: '1512',
  },
  {
    hsnCode: '1517',
    description: 'Margarine; edible mixtures of fats or oils',
    gstRate: '12',
    cessRate: '0',
    chapter: '15',
    heading: '1517',
  },
  // Chapter 17 — Sugar
  {
    hsnCode: '1701',
    description: 'Cane or beet sugar and chemically pure sucrose',
    gstRate: '5',
    cessRate: '0',
    chapter: '17',
    heading: '1701',
  },
  // Chapter 19 — Bakery / cereal preparations
  {
    hsnCode: '1905',
    description: 'Bread, pastry, cakes, biscuits and other bakers’ wares',
    gstRate: '18',
    cessRate: '0',
    chapter: '19',
    heading: '1905',
  },
  // Chapter 20 — Prepared/preserved vegetables, fruit (packaged/canned)
  {
    hsnCode: '2005',
    description: 'Other vegetables prepared or preserved (canned)',
    gstRate: '12',
    cessRate: '0',
    chapter: '20',
    heading: '2005',
  },
  // Chapter 21 — Misc. edible preparations
  {
    hsnCode: '2101',
    description: 'Extracts, essences and concentrates of coffee, tea or maté',
    gstRate: '18',
    cessRate: '0',
    chapter: '21',
    heading: '2101',
  },
  {
    hsnCode: '2106',
    description: 'Food preparations not elsewhere specified or included',
    gstRate: '18',
    cessRate: '0',
    chapter: '21',
    heading: '2106',
  },
  // Chapter 22 — Beverages
  {
    hsnCode: '2201',
    description: 'Waters, including natural or artificial mineral waters',
    gstRate: '18',
    cessRate: '0',
    chapter: '22',
    heading: '2201',
  },
  {
    hsnCode: '2202',
    description: 'Waters with added sugar/flavour; other non-alcoholic beverages',
    gstRate: '28',
    cessRate: '12',
    chapter: '22',
    heading: '2202',
  },
  // Chapter 25 — Salt
  {
    hsnCode: '2501',
    description: 'Salt (including table salt and denatured salt)',
    gstRate: '0',
    cessRate: '0',
    chapter: '25',
    heading: '2501',
  },
  // Chapter 33/34 — Personal care, soap, household cleaning
  {
    hsnCode: '3304',
    description: 'Beauty or make-up and skin-care preparations',
    gstRate: '18',
    cessRate: '0',
    chapter: '33',
    heading: '3304',
  },
  {
    hsnCode: '3401',
    description: 'Soap; organic surface-active products for washing the skin',
    gstRate: '18',
    cessRate: '0',
    chapter: '34',
    heading: '3401',
  },
  {
    hsnCode: '3402',
    description: 'Washing and cleaning preparations (detergents)',
    gstRate: '18',
    cessRate: '0',
    chapter: '34',
    heading: '3402',
  },
];
