import { and, eq, sql } from 'drizzle-orm';
import { debitNotes } from '@erp/db';
import type { ErpDatabase } from '@erp/db';
import { BusinessError, NotFoundError } from '@erp/types';

export interface ApplyDebitNoteParams {
  id: number;
  tenantId: number;
  amount: number;
  notes?: string | undefined;
}

// A debit note (auto-generated by PurchaseReturnService.approve()) previously had no path
// to ever leave status 'OPEN' — appliedAmount/balanceAmount were set once at creation and
// never touched again anywhere in the codebase, even though the return itself already
// correctly reduced projectionSupplierBalance. This service closes that gap: it lets AP
// staff record that a credit note's value has been matched against a specific supplier
// bill/payment (e.g. "adjusted against Payment #123" in `notes`), which is what a real
// accounts-payable clerk needs when reconciling the supplier statement — an OPEN debit
// note with no way to ever mark it used looks, from a reporting standpoint, identical to
// one nobody has gotten around to using yet.
export class DebitNoteService {
  constructor(private db: ErpDatabase) {}

  async apply(params: ApplyDebitNoteParams): Promise<void> {
    const { id, tenantId, amount, notes } = params;
    if (amount <= 0) throw new BusinessError('INVALID_AMOUNT', 'Apply amount must be positive');

    await this.db.transaction(async (trx) => {
      const [dn] = await trx
        .select()
        .from(debitNotes)
        .where(and(eq(debitNotes.id, id), eq(debitNotes.tenantId, tenantId)))
        .for('update');
      if (!dn) throw new NotFoundError('DebitNote', id);
      if (dn.status !== 'OPEN' && dn.status !== 'PARTIALLY_APPLIED')
        throw new BusinessError(
          'INVALID_STATUS',
          `Cannot apply a debit note in status ${dn.status}`
        );

      const balanceAmount = parseFloat(String(dn.balanceAmount));
      if (amount > balanceAmount + 0.001)
        throw new BusinessError(
          'AMOUNT_EXCEEDS_BALANCE',
          `Apply amount ${amount} exceeds remaining debit note balance ${balanceAmount}`
        );

      const newBalance = Math.round((balanceAmount - amount) * 100) / 100;
      const newStatus = newBalance <= 0.001 ? 'APPLIED' : 'PARTIALLY_APPLIED';
      const combinedNotes = [dn.notes, notes].filter(Boolean).join(' | ') || undefined;

      await trx
        .update(debitNotes)
        .set({
          appliedAmount: sql`${debitNotes.appliedAmount} + ${amount}`,
          balanceAmount: String(Math.max(0, newBalance)),
          status: newStatus,
          notes: combinedNotes,
          updatedAt: new Date(),
        })
        .where(and(eq(debitNotes.id, id), eq(debitNotes.tenantId, tenantId)));
    });
  }
}
