apiVersion: v1
kind: Namespace
metadata:
  name: erp-system
  labels:
    name: erp-system
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: erp-infra
  labels:
    name: erp-infra
