import type { TourDefinition } from '../../schema.js';
import { PERMISSIONS } from '../../../../constants/permissions.js';

// Deep-dive companion to `sales-invoices-overview` (the 4-step quick tour). Every claim below
// was verified against real code before writing — not invented — see the Sales-module audit
// this tour was built from: InvoiceService.confirm/create (apps/sales-service),
// InvoiceAccountingConsumer/CogsAccountingConsumer (apps/accounting-service),
// InvoiceGstConsumer (apps/gst-service), and ReportEngine.ts's stock-valuation query
// (apps/report-service) for the projection_stock_level lag. Where the code's behavior is
// genuinely surprising (stock lag, two separate journal entries, credit check vs balance
// timing), that's called out explicitly rather than smoothed over — this is what makes tour
// content trustworthy instead of decorative.
const tour: TourDefinition = {
  id: 'sales-invoices-complete-guide',
  version: 1,
  type: 'complete',
  title: 'Invoices — complete guide',
  description:
    'A deep walkthrough of Invoices: why this page exists, the full create-to-cash workflow, what it does to stock/accounting/GST/reports, and real mistakes to avoid.',
  module: 'sales',
  estimatedMinutes: 8,
  requiredPermissions: [PERMISSIONS.INVOICE_VIEW],
  steps: [
    {
      id: 'purpose',
      route: 'sales/invoices',
      title: 'Why this page exists',
      body: 'An invoice is your legally binding, GST-compliant bill to a customer — the document that actually books revenue and creates a receivable. Sales staff create them; whoever confirms one (usually a supervisor or accountant) is committing real stock and real accounting entries, so that role often sits with a different person than the one who drafted it.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
    },
    {
      id: 'when-to-use',
      route: 'sales/invoices',
      title: 'When to use an Invoice — not a Quotation or Challan',
      body: "Use an Invoice when you're ready to actually bill the customer. A Quotation is a non-binding price offer — nothing happens to stock or accounts until it's converted. A Delivery Challan is a pure dispatch record — goods can leave the warehouse on a challan with zero accounting effect. Only an invoice, once confirmed, moves stock and money.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
    },
    {
      id: 'prerequisites',
      route: 'sales/invoices',
      title: 'Before you start',
      body: "A few things need to be true before creating an invoice, or you'll hit an error mid-way through.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
      calloutTitle: 'Before you start',
      calloutVariant: 'warning',
      businessImpact: [
        'The customer must already exist, with the correct state set — that state drives whether this invoice charges CGST+SGST or IGST.',
        "Your organization's own GSTIN/state should be set under Settings → Organization — until it is, GST splitting silently falls back to a Maharashtra default.",
        "Items need a sale price and GST rate on the item master, or you'll be typing them in by hand on every line.",
        "Stock isn't checked when you save a draft — only when you confirm. A draft can sit against an item that's actually out of stock.",
      ],
    },
    {
      id: 'list-search',
      route: 'sales/invoices',
      target: '[data-tour-id="sales-invoices-search-input"]',
      title: 'Finding an invoice',
      body: 'Search matches the invoice number only — not the customer name or amount. For a fast lookup by customer, the status filter next to it narrows the list first.',
      placement: 'bottom',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
    },
    {
      id: 'list-status',
      route: 'sales/invoices',
      target: '[data-tour-id="sales-invoices-status-filter"]',
      title: 'What each status means',
      body: 'DRAFT = saved but not yet real (no stock/accounting effect). CONFIRMED = booked, awaiting payment. PARTIALLY_PAID / PAID = payment recorded and allocated. OVERDUE = confirmed and past its due date with balance still owing. CANCELLED = reversed.',
      placement: 'bottom',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
    },
    {
      id: 'create-customer',
      route: 'sales/invoices/new',
      target: '[data-tour-id="sales-invoice-new-customer-select"]',
      title: 'Selecting the customer',
      body: "Search and pick the customer. This one field decides the invoice's Place of Supply — and Place of Supply is what decides the GST split. Example: a Maharashtra seller billing a Maharashtra customer charges CGST+SGST; the same seller billing a Gujarat customer charges IGST instead.",
      placement: 'bottom',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_CREATE,
    },
    {
      id: 'create-item',
      route: 'sales/invoices/new',
      target: '[data-tour-id="sales-invoice-new-item-search"]',
      title: 'Adding items and pricing',
      body: 'Search and click an item to add it as a line. Price, discount %, and GST rate all prefill from the item master but stay editable per line — a manager can override a price under a permission gate, but changing the GST rate per line is a compliance decision, not a pricing one. Check with accounts before doing that, not after.',
      placement: 'top',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_CREATE,
    },
    {
      id: 'create-save',
      route: 'sales/invoices/new',
      target: '[data-tour-id="sales-invoice-new-save-button"]',
      title: 'Save as Draft',
      body: "This creates the invoice as a DRAFT — it does not touch stock or accounting yet. The customer's credit limit is checked right now, at save time, but that means two separate drafts against the same customer can both individually pass the credit check before either is confirmed.",
      placement: 'top',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_CREATE,
    },
    {
      id: 'detail-confirm',
      route: 'sales/invoices',
      title: 'On the invoice detail page: Confirm Invoice',
      body: "Open any DRAFT invoice and you'll see this button — the single most important one on the whole page. Confirming assigns the real invoice number, deducts stock at the chosen warehouse, posts the accounting entries, records the GST ledger entry, and increases the customer's outstanding balance — all at once. If stock ran out since you saved the draft, confirming will fail rather than let stock go negative.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_CREATE,
    },
    {
      id: 'detail-payment',
      route: 'sales/invoices',
      title: 'On the invoice detail page: Record Payment',
      body: "Shown once an invoice is CONFIRMED or PARTIALLY_PAID. It opens the payment form pre-filled with this invoice's customer and remaining balance — the fastest way to collect against a specific invoice rather than starting a payment from scratch.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.PAYMENT_CREATE,
    },
    {
      id: 'detail-print',
      route: 'sales/invoices',
      title: 'On the invoice detail page: Print / Download PDF',
      body: "Generates the real, customer-facing invoice document. Only available once an invoice is confirmed (or later) — a DRAFT has no official invoice number yet, so there's nothing valid to print.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
    },
    {
      id: 'detail-cancel',
      route: 'sales/invoices',
      title: 'On the invoice detail page: Cancel',
      body: 'Works on DRAFT or CONFIRMED invoices and always asks for a reason. Cancelling a confirmed invoice automatically reverses its accounting entry — but it does not automatically put returned goods back on your shelf. If the customer physically has the goods, use a Sale Return instead so stock comes back correctly.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_CANCEL,
    },
    {
      id: 'business-impact',
      route: 'sales/invoices',
      title: 'What confirming an invoice touches across the business',
      body: 'One click, six places react.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
      calloutTitle: 'Business impact',
      calloutVariant: 'info',
      businessImpact: [
        'Inventory: available stock is deducted immediately at the invoiced warehouse — not when you saved the draft.',
        'Accounting: two journal entries post — Accounts Receivable vs. Sales Revenue (plus GST payable), and separately Cost of Goods Sold vs. Inventory.',
        'GST: a ledger entry is recorded for this sale, feeding GSTR-1/GSTR-9 filings.',
        "Reports: Trial Balance, AR Aging, and Sales Analytics reflect it immediately. Stock Valuation is the exception — it reads from a separate snapshot that sales activity doesn't update in real time, so it can visibly lag until the next reconciliation.",
        "Dashboard: today's sales and revenue widgets include it as soon as it's confirmed.",
        "Customer Outstanding: the customer's balance increases the moment you confirm — not when you save the draft.",
      ],
    },
    {
      id: 'common-mistakes',
      route: 'sales/invoices',
      title: 'Common mistakes',
      body: 'These are the ones that cause real support tickets.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
      calloutTitle: 'Common mistakes',
      calloutVariant: 'warning',
      businessImpact: [
        'Treating "Save as Draft" as "the sale is done" — nothing moves until you Confirm.',
        'Confirming without checking stock first on fast-moving items, then having the confirm fail mid-workflow.',
        "Picking the wrong customer state and only noticing when GST doesn't split the way the accountant expects.",
        'Cancelling instead of returning when the customer already has the goods — Cancel reverses the books but not physical stock.',
        'Looking for an "Edit" button on a saved invoice — there isn\'t one. Fix a mistake by Cancelling it and creating a new one (or Duplicate it to reuse the line items).',
      ],
    },
    {
      id: 'best-practices',
      route: 'sales/invoices',
      title: 'Best practices',
      body: 'How experienced teams run this page day to day.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
      calloutTitle: 'Best practices',
      calloutVariant: 'success',
      businessImpact: [
        'Convert from an Accepted Quotation or a Dispatched Delivery Challan instead of retyping — customer, items, and pricing carry over.',
        "Confirm invoices the same day you create them — a backlog of drafts means your books and stock don't reflect what you actually sold.",
        'Use Duplicate for repeat invoices to the same customer instead of rebuilding line items from scratch.',
        'Review PARTIALLY_PAID and OVERDUE invoices on a schedule — that list is your real collections follow-up queue.',
      ],
    },
  ],
};

export default tour;
