import type { TourDefinition } from '../../schema.js';
import { PERMISSIONS } from '../../../../constants/permissions.js';

// Deep-dive companion to `sales-quotations-overview`. Grounded against QuotationService.ts
// (apps/sales-service) — `accept()` only flips a status column, `convert()` fires an outbox
// event with no accounting/inventory/GST consumer anywhere in the codebase. A quotation, by
// itself, never touches the books — that's the one fact this tour exists to make unmistakable.
const tour: TourDefinition = {
  id: 'sales-quotations-complete-guide',
  version: 1,
  type: 'complete',
  title: 'Quotations — complete guide',
  description:
    'Why quotations exist, the send-accept-convert lifecycle, and why nothing financial happens until an accepted quotation actually becomes an invoice.',
  module: 'sales',
  estimatedMinutes: 6,
  requiredPermissions: [PERMISSIONS.INVOICE_VIEW],
  steps: [
    {
      id: 'purpose',
      route: 'sales/quotations',
      title: 'Why this page exists',
      body: "A quotation is a non-binding price offer — a formal way to give a customer pricing before they've committed to buy. It's what a sales rep sends during negotiation: a bulk-order inquiry, a first-time customer wanting a written quote, a price that needs manager sign-off before it becomes a real sale.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
    },
    {
      id: 'when-to-use',
      route: 'sales/quotations',
      title: 'When to use a Quotation instead of an Invoice',
      body: "Use a Quotation whenever the customer hasn't committed yet. The moment they agree, Accept it, Convert it, then create and confirm the invoice from it — at no point before that final Confirm does a quotation touch stock, accounting, or GST.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
    },
    {
      id: 'prerequisites',
      route: 'sales/quotations',
      title: 'Before you start',
      body: 'Lighter requirements than an invoice, since nothing here commits stock or money yet.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
      calloutTitle: 'Before you start',
      calloutVariant: 'warning',
      businessImpact: [
        "The customer must exist in the system — quotations can't be sent to a name typed in free text.",
        'Items should have a sale price and GST rate set on the item master so the quoted total is realistic.',
        "There's no credit-limit check on a quotation — that check only happens when the resulting invoice is created.",
      ],
    },
    {
      id: 'list-status',
      route: 'sales/quotations',
      target: '[data-tour-id="sales-quotations-status-filter"]',
      title: 'What each status means',
      body: 'DRAFT → SENT (customer notified) → VIEWED (they opened it) → ACCEPTED or REJECTED → CONVERTED (an invoice was created from it). A red "Valid Until" date on the list is just a visual cue that today is past that date — it does not change the underlying status by itself; an overdue-looking quotation can still be Accepted or Rejected exactly as before.',
      placement: 'bottom',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
    },
    {
      id: 'create-customer',
      route: 'sales/quotations/new',
      target: '[data-tour-id="sales-quotation-new-customer-select"]',
      title: 'Selecting the customer',
      body: "Same customer picker as Invoices — search and select. The state on the customer record still drives the eventual GST split once this becomes an invoice, so it's worth getting right here, not just fixing it later.",
      placement: 'bottom',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_CREATE,
    },
    {
      id: 'create-item',
      route: 'sales/quotations/new',
      target: '[data-tour-id="sales-quotation-new-item-search"]',
      title: 'Adding items and pricing',
      body: "Add items the same way as an invoice. Use the Terms & Conditions field (below the line items) for validity period and payment terms — that's what it's there for, rather than folding that into Notes where it's easy to miss.",
      placement: 'top',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_CREATE,
    },
    {
      id: 'create-save',
      route: 'sales/quotations/new',
      target: '[data-tour-id="sales-quotation-new-save-button"]',
      title: 'Save as Draft',
      body: 'Creates the quotation as a DRAFT. Nothing has been sent to the customer yet, and nothing anywhere in accounting, inventory, or GST has been touched.',
      placement: 'top',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_CREATE,
    },
    {
      id: 'detail-send',
      route: 'sales/quotations',
      title: 'On the quotation detail page: Send',
      body: "Moves the quotation from DRAFT to SENT. Only available while it's still a DRAFT — once sent, editing means creating a fresh quotation, not changing this one.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_CREATE,
    },
    {
      id: 'detail-accept',
      route: 'sales/quotations',
      title: 'On the quotation detail page: Accept',
      body: 'Marks the quotation ACCEPTED once the customer has agreed. This is purely a status change — it does not create an invoice, reserve stock, or post anything to accounting by itself.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.QUOTATION_CONVERT,
    },
    {
      id: 'detail-convert',
      route: 'sales/quotations',
      title: 'On the quotation detail page: Convert to Invoice',
      body: "Marks the quotation CONVERTED and takes you straight to a new invoice form, pre-filled with this quotation's customer and line items. This is still not the moment stock or accounting move — that happens only when you Confirm the invoice it creates.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.QUOTATION_CONVERT,
    },
    {
      id: 'business-impact',
      route: 'sales/quotations',
      title: 'What a quotation actually touches',
      body: "Less than you might expect — and that's by design.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
      calloutTitle: 'Business impact',
      calloutVariant: 'info',
      businessImpact: [
        'Inventory: no effect, at any status, ever — not even ACCEPTED or CONVERTED.',
        'Accounting: no journal entry is ever posted from a quotation alone.',
        'GST: no ledger entry — GST only enters the picture once an invoice from this quotation is confirmed.',
        "Reports: quotations don't appear in Sales Analytics, Trial Balance, or AR Aging — only the resulting invoice does.",
        'Dashboard: not counted in revenue widgets until it becomes a confirmed invoice.',
        'Customer Outstanding: unaffected — a quotation never changes what a customer owes.',
      ],
    },
    {
      id: 'common-mistakes',
      route: 'sales/quotations',
      title: 'Common mistakes',
      body: 'The gap between "accepted" and "booked" trips people up more than anything else here.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
      calloutTitle: 'Common mistakes',
      calloutVariant: 'warning',
      businessImpact: [
        'Treating ACCEPTED as "the sale is booked" — it isn\'t, until an invoice is created from it and confirmed.',
        'Assuming a quotation with a red, past-due "Valid Until" date has automatically expired — it hasn\'t; it can still be accepted or rejected.',
        'Leaving accepted quotations un-converted for days — the sales pipeline looks healthier than the books actually are.',
        'Looking for an "Edit" button on a sent quotation — there isn\'t one. If the price or items need to change, create a new quotation.',
      ],
    },
    {
      id: 'best-practices',
      route: 'sales/quotations',
      title: 'Best practices',
      body: 'Keep the pipeline and the books in sync.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.INVOICE_VIEW,
      calloutTitle: 'Best practices',
      calloutVariant: 'success',
      businessImpact: [
        "Convert and confirm the same day a quotation is accepted — don't let pricing go stale between acceptance and billing.",
        'Reject explicitly instead of leaving a dead quotation sitting as SENT — it keeps status-based reports honest.',
        'Use Terms & Conditions for validity/payment terms so they travel with the document when printed or shared.',
      ],
    },
  ],
};

export default tour;
