import type { TourDefinition } from '../../schema.js';
import { PERMISSIONS } from '../../../../constants/permissions.js';

// Deep-dive companion to `reports-overview`. Grounded against a comprehensive, column-by-column
// audit of every one of the 77 report cases in apps/report-service/src/domain/ReportEngine.ts,
// cross-checked against the real Drizzle schema. 43 of 77 (56%) reference columns that don't
// exist and will throw a Postgres error at runtime. This guide exists to give precise,
// per-category guidance so the module remains genuinely useful despite that — trust the right
// reports, avoid the wrong ones, and know what "this report failed" actually means.
const tour: TourDefinition = {
  id: 'reports-complete-guide',
  version: 1,
  type: 'complete',
  title: 'Reports — complete guide',
  description:
    "Which of the 77 reports are safe to trust today, which will error, and how to work around the gap until they're fixed.",
  module: 'reports',
  estimatedMinutes: 7,
  requiredPermissions: [PERMISSIONS.REPORT_VIEW],
  steps: [
    {
      id: 'purpose',
      route: 'reports',
      title: 'Why this page exists',
      body: 'A single browsable catalog of every report in the system — 77 definitions across Sales, Purchase, Inventory, Financial, HR, GST, and Analytics — plus 3 chart dashboards and a scheduling system for recurring email delivery.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
    },
    {
      id: 'permission-filtered',
      route: 'reports',
      title: 'You only see what you can actually run',
      body: "The hub now filters to reports matching your real permissions — previously it listed all 77 regardless, and you'd only discover you were blocked after filling in parameters and clicking Run.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
    },
    {
      id: 'the-real-finding',
      route: 'reports',
      title: 'A column-by-column audit found 43 of 77 reports are broken',
      body: "Every report case was checked against the real database schema. 43 reference a table or column that doesn't exist and will fail with a server error the moment you run them. This isn't a permissions issue or something you can work around by changing filters — it's a genuine data-layer bug in those specific reports.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
      calloutTitle: 'Business impact',
      calloutVariant: 'warning',
    },
    {
      id: 'category-breakdown',
      route: 'reports',
      title: 'Where the breakage concentrates',
      body: 'Inventory: all 13 reports broken. Purchase: 9 of 12. Sales: 9 of 19. Financial: 8 of 15 (mostly the older ledger-style reports — Day Book, Account Ledger, Bank Book, Journal Report, TDS Report, Depreciation Schedule). HR: 4 of 6 (Payroll Report, Leave Report, Employee Master Report, Alteration Report). GST: 0 of 6 — fully reliable. Analytics dashboards: 0 of 6 — fully reliable.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
    },
    {
      id: 'what-still-works-in-each-category',
      route: 'reports',
      title: "What's genuinely safe in the affected categories",
      body: 'Sales: Sales Register, By Customer, By Category, By Salesperson, Outstanding Receivables, Quotation Conversion, Top Selling Items, Loyalty Points, Discount Report. Purchase: Purchase Register, By Supplier, Supplier Ledger, Landed Cost Report. Financial: Trial Balance, P&L, Balance Sheet, Cash Flow, Expense Analysis, Profit Center Report, Fund Flow, AR Aging. HR: Attendance Report, Tailor Work Log.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
    },
    {
      id: 'dedicated-pages-are-safe',
      route: 'reports',
      title: 'The 5 dedicated pages are separately verified',
      body: "AR Aging, AP Aging, Sales Analytics, Inventory Analytics, and HR Analytics each have their own custom page and (for the aging reports) their own dedicated backend endpoint — they're not affected by the broken generic-viewer cases sharing similar names, and were checked independently.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
    },
    {
      id: 'run-a-report',
      route: 'reports',
      target: '[data-tour-id="reports-viewer-run-button"]',
      title: 'Running a report',
      body: "Set parameters, then Run Report. Some reports queue in the background (you'll see a \"generating your data\" message) rather than returning instantly — that's expected for reports that scan a lot of data, not a sign something's wrong.",
      placement: 'bottom',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
    },
    {
      id: 'export',
      route: 'reports',
      target: '[data-tour-id="reports-viewer-export-csv-button"]',
      title: 'Export',
      body: 'CSV and Excel are both real file downloads, now correctly showing an error if the server rejects the request instead of silently downloading a corrupted or empty file.',
      placement: 'bottom',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
    },
    {
      id: 'scheduling',
      route: 'reports/schedules',
      target: '[data-tour-id="reports-schedules-create-button"]',
      title: 'Scheduling a report',
      body: "A genuinely working cron + email pipeline — but the reports it can schedule are the same 77 definitions, so the same broken/working split applies. Scheduling a broken report won't fail loudly; the job will error and no email goes out. Stick to the reports listed as reliable above.",
      placement: 'bottom',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_SCHEDULE,
    },
    {
      id: 'common-mistakes',
      route: 'reports',
      title: 'Common mistakes',
      body: "Don't assume a report error means you did something wrong.",
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
      calloutTitle: 'Common mistakes',
      calloutVariant: 'warning',
      businessImpact: [
        'Retrying a broken report with different filters — the failure is structural (a missing column), not filter-dependent, so it will fail every time regardless of what you enter.',
        "Assuming a report with a similar name to a known-broken one is also broken — check the specific list above, since e.g. Purchase Register works while Purchase by Item doesn't.",
        "Scheduling a report you haven't successfully run manually first — verify it works before automating its delivery.",
      ],
    },
    {
      id: 'best-practices',
      route: 'reports',
      title: 'Best practices',
      body: 'Verify before you rely on a number.',
      placement: 'center',
      mode: 'informational',
      requiredPermission: PERMISSIONS.REPORT_VIEW,
      calloutTitle: 'Best practices',
      calloutVariant: 'success',
      businessImpact: [
        "For anything Inventory-related, use the module's own pages (Stock, Valuation) rather than the Reports hub's Inventory category — every report there is currently broken.",
        "For financial statements, trust Trial Balance/P&L/Balance Sheet/Cash Flow specifically — they're verified correct, unlike their ledger-detail siblings (Day Book, Account Ledger, Bank Book).",
        "If you need a report that's currently broken, that's worth reporting to your team as a real gap — it's not something you can fix by changing how you use the page.",
      ],
    },
  ],
};

export default tour;
