CREATE TABLE IF NOT EXISTS expense_sub_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    expense_category_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_expense_sub_categories_expense_category
        FOREIGN KEY (expense_category_id) REFERENCES expense_categories (id)
);

CREATE INDEX IF NOT EXISTS idx_expense_sub_categories_expense_category_id
    ON expense_sub_categories (expense_category_id);
