-- Per-user connected email account, used so outbound email is sent through the
-- individual user's own mailbox (via their SMTP credentials) instead of the
-- shared organization sender address.

CREATE TABLE IF NOT EXISTS user_email_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    from_address VARCHAR(255) NOT NULL,
    smtp_host VARCHAR(255) NOT NULL,
    smtp_port INTEGER NOT NULL,
    smtp_username VARCHAR(255) NOT NULL,
    smtp_password_encrypted TEXT NOT NULL,
    use_starttls BOOLEAN NOT NULL DEFAULT TRUE,
    use_ssl BOOLEAN NOT NULL DEFAULT FALSE,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_user_email_accounts_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_user_email_accounts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_user_email_accounts_user UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_user_email_accounts_organization ON user_email_accounts (organization_id);
