-- Fresh database baseline schema for Sale ERP.
-- Hibernate is configured with ddl-auto=validate, so Flyway owns table creation.

CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    logo_url VARCHAR(500),
    phone VARCHAR(20),
    gst_number VARCHAR(20),
    address_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_organizations_name UNIQUE (name),
    CONSTRAINT uk_organizations_address UNIQUE (address_id)
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    organization_id BIGINT,
    CONSTRAINT fk_roles_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    group_name VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    endpoint VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_permissions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    user_name VARCHAR(50) NOT NULL,
    email VARCHAR(150) NOT NULL,
    mobile_no VARCHAR(20),
    profile_image_url VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    role_id BIGINT NOT NULL,
    organization_id BIGINT,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_user_name UNIQUE (user_name),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS role_permission_mapping (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_mapping_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_role_permission_mapping_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

CREATE TABLE IF NOT EXISTS user_permission_mapping (
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, permission_id),
    CONSTRAINT fk_user_permission_mapping_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_permission_mapping_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    iso_code VARCHAR(10),
    currency_code VARCHAR(10),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    country_id BIGINT,
    state_name VARCHAR(100) NOT NULL,
    state_code VARCHAR(20),
    gst_code VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_states_country FOREIGN KEY (country_id) REFERENCES countries (id)
);

CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    contact_type VARCHAR(50),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(150),
    phone VARCHAR(20),
    mobile VARCHAR(20),
    whatsapp_no VARCHAR(20),
    gst_number VARCHAR(30),
    pan_number VARCHAR(20),
    credit_limit NUMERIC(15,2),
    opening_balance NUMERIC(15,2),
    opening_balance_type VARCHAR(20),
    is_wholesale BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_contacts_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    contact_id BIGINT,
    address_type VARCHAR(50),
    address_line1 VARCHAR(250),
    address_line2 VARCHAR(250),
    city VARCHAR(100),
    state_id BIGINT,
    pincode VARCHAR(20),
    CONSTRAINT fk_addresses_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_addresses_contact FOREIGN KEY (contact_id) REFERENCES contacts (id),
    CONSTRAINT fk_addresses_state FOREIGN KEY (state_id) REFERENCES states (id)
);

ALTER TABLE organizations
    ADD CONSTRAINT fk_organizations_address FOREIGN KEY (address_id) REFERENCES addresses (id);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_categories_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS sub_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    category_id BIGINT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_sub_categories_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sub_categories_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    category_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_brands_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    short_name VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_units_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    item_name VARCHAR(150) NOT NULL,
    item_code VARCHAR(50),
    sku VARCHAR(80),
    hsn_code VARCHAR(30),
    category_id BIGINT,
    sub_category_id BIGINT,
    brand_id BIGINT,
    base_unit_id BIGINT,
    description VARCHAR(500),
    image_url VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'OUT_OF_STOCK',
    CONSTRAINT chk_items_status CHECK (status IN ('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK')),
    CONSTRAINT fk_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_items_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_items_sub_category FOREIGN KEY (sub_category_id) REFERENCES sub_categories (id),
    CONSTRAINT fk_items_brand FOREIGN KEY (brand_id) REFERENCES brands (id),
    CONSTRAINT fk_items_base_unit FOREIGN KEY (base_unit_id) REFERENCES units (id)
);

CREATE TABLE IF NOT EXISTS item_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    item_id BIGINT,
    purchase_price NUMERIC(15,2),
    purchase_price_with_tax NUMERIC(15,2),
    tax_percentage NUMERIC(5,2),
    sale_price NUMERIC(15,2),
    wholesale_price NUMERIC(15,2),
    mrp NUMERIC(15,2),
    msp NUMERIC(15,2),
    discount_percentage NUMERIC(5,2),
    profit_margin NUMERIC(5,2),
    effective_from DATE,
    CONSTRAINT fk_item_prices_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS item_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    item_id BIGINT,
    batch_no VARCHAR(80),
    manufacturing_date DATE,
    expiry_date DATE,
    CONSTRAINT fk_item_batches_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    warehouse_code VARCHAR(50),
    description VARCHAR(500),
    address VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_warehouses_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    item_id BIGINT,
    warehouse_id BIGINT,
    batch_id BIGINT,
    available_qty NUMERIC(15,3),
    reserved_qty NUMERIC(15,3),
    minimum_stock NUMERIC(15,3),
    reorder_level NUMERIC(15,3),
    rack_location VARCHAR(100),
    CONSTRAINT fk_stock_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_stock_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_stock_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS stock_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    item_id BIGINT,
    warehouse_id BIGINT,
    batch_id BIGINT,
    transaction_type VARCHAR(50),
    reference_id BIGINT,
    qty_in NUMERIC(15,3),
    qty_out NUMERIC(15,3),
    balance_qty NUMERIC(15,3),
    transaction_date TIMESTAMP(6),
    remarks VARCHAR(500),
    CONSTRAINT fk_stock_transactions_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_transactions_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_stock_transactions_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_stock_transactions_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS shipping_carriers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150),
    mobile VARCHAR(20),
    whatsapp_no VARCHAR(20),
    address VARCHAR(500),
    note VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_shipping_carriers_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    purchase_no VARCHAR(50) NOT NULL,
    supplier_id BIGINT,
    purchase_date DATE,
    reference_no VARCHAR(100),
    warehouse_id BIGINT,
    carrier_id BIGINT,
    state_id BIGINT,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    round_off NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    paid_amount NUMERIC(15,2),
    due_amount NUMERIC(15,2),
    status VARCHAR(50),
    notes VARCHAR(500),
    CONSTRAINT fk_purchases_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchases_supplier FOREIGN KEY (supplier_id) REFERENCES contacts (id),
    CONSTRAINT fk_purchases_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_purchases_carrier FOREIGN KEY (carrier_id) REFERENCES shipping_carriers (id),
    CONSTRAINT fk_purchases_state FOREIGN KEY (state_id) REFERENCES states (id)
);

CREATE TABLE IF NOT EXISTS purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    purchase_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    unit_price NUMERIC(15,2),
    discount_percent NUMERIC(5,2),
    discount_amount NUMERIC(15,2),
    tax_percent NUMERIC(5,2),
    tax_amount NUMERIC(15,2),
    total_amount NUMERIC(15,2),
    CONSTRAINT fk_purchase_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchase_items_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_purchase_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_purchase_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS purchase_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    return_no VARCHAR(50) NOT NULL,
    purchase_id BIGINT,
    supplier_id BIGINT,
    return_date DATE,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    notes VARCHAR(500),
    CONSTRAINT fk_purchase_returns_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchase_returns_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_purchase_returns_supplier FOREIGN KEY (supplier_id) REFERENCES contacts (id)
);

CREATE TABLE IF NOT EXISTS purchase_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    purchase_return_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    rate NUMERIC(15,2),
    amount NUMERIC(15,2),
    CONSTRAINT fk_purchase_return_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchase_return_items_return FOREIGN KEY (purchase_return_id) REFERENCES purchase_returns (id),
    CONSTRAINT fk_purchase_return_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_purchase_return_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    invoice_no VARCHAR(50) NOT NULL,
    invoice_date DATE,
    customer_id BIGINT,
    warehouse_id BIGINT,
    state_id BIGINT,
    sales_person_id BIGINT,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    round_off NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    paid_amount NUMERIC(15,2),
    due_amount NUMERIC(15,2),
    status VARCHAR(50),
    notes VARCHAR(500),
    CONSTRAINT fk_sales_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES contacts (id),
    CONSTRAINT fk_sales_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_sales_state FOREIGN KEY (state_id) REFERENCES states (id),
    CONSTRAINT fk_sales_sales_person FOREIGN KEY (sales_person_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS sales_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    sale_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    unit_price NUMERIC(15,2),
    discount_percent NUMERIC(5,2),
    discount_amount NUMERIC(15,2),
    tax_percent NUMERIC(5,2),
    tax_amount NUMERIC(15,2),
    total_amount NUMERIC(15,2),
    CONSTRAINT fk_sales_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_items_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_sales_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_sales_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS sales_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    return_no VARCHAR(50) NOT NULL,
    sale_id BIGINT,
    customer_id BIGINT,
    return_date DATE,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    notes VARCHAR(500),
    CONSTRAINT fk_sales_returns_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_returns_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_sales_returns_customer FOREIGN KEY (customer_id) REFERENCES contacts (id)
);

CREATE TABLE IF NOT EXISTS sales_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    sales_return_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    rate NUMERIC(15,2),
    amount NUMERIC(15,2),
    CONSTRAINT fk_sales_return_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_return_items_return FOREIGN KEY (sales_return_id) REFERENCES sales_returns (id),
    CONSTRAINT fk_sales_return_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_sales_return_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    quotation_no VARCHAR(50) NOT NULL,
    quotation_date DATE,
    valid_until DATE,
    customer_id BIGINT,
    warehouse_id BIGINT,
    state_id BIGINT,
    sales_person_id BIGINT,
    converted_sale_id BIGINT,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    round_off NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    status VARCHAR(50),
    notes VARCHAR(500),
    CONSTRAINT fk_quotations_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_quotations_customer FOREIGN KEY (customer_id) REFERENCES contacts (id),
    CONSTRAINT fk_quotations_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_quotations_state FOREIGN KEY (state_id) REFERENCES states (id),
    CONSTRAINT fk_quotations_sales_person FOREIGN KEY (sales_person_id) REFERENCES users (id),
    CONSTRAINT fk_quotations_converted_sale FOREIGN KEY (converted_sale_id) REFERENCES sales (id)
);

CREATE TABLE IF NOT EXISTS quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    quotation_id BIGINT,
    item_id BIGINT,
    qty NUMERIC(15,3),
    unit_price NUMERIC(15,2),
    discount_percent NUMERIC(5,2),
    discount_amount NUMERIC(15,2),
    tax_percent NUMERIC(5,2),
    tax_amount NUMERIC(15,2),
    total_amount NUMERIC(15,2),
    CONSTRAINT fk_quotation_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_quotation_items_quotation FOREIGN KEY (quotation_id) REFERENCES quotations (id),
    CONSTRAINT fk_quotation_items_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_payment_methods_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    payment_no VARCHAR(50) NOT NULL,
    payment_type VARCHAR(50),
    payment_method_id BIGINT,
    contact_id BIGINT,
    amount NUMERIC(15,2),
    payment_date DATE,
    reference_no VARCHAR(100),
    notes VARCHAR(500),
    CONSTRAINT fk_payments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_payments_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id),
    CONSTRAINT fk_payments_contact FOREIGN KEY (contact_id) REFERENCES contacts (id)
);

CREATE TABLE IF NOT EXISTS sales_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    sale_id BIGINT,
    payment_id BIGINT,
    amount NUMERIC(15,2),
    CONSTRAINT fk_sales_payments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_payments_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_sales_payments_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE TABLE IF NOT EXISTS purchase_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    purchase_id BIGINT,
    payment_id BIGINT,
    amount NUMERIC(15,2),
    CONSTRAINT fk_purchase_payments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchase_payments_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_purchase_payments_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE TABLE IF NOT EXISTS bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    bank_name VARCHAR(150),
    account_name VARCHAR(150),
    account_number VARCHAR(50),
    ifsc_code VARCHAR(20),
    branch_name VARCHAR(150),
    opening_balance NUMERIC(15,2),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_bank_accounts_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS bank_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    bank_account_id BIGINT,
    payment_id BIGINT,
    transaction_type VARCHAR(50),
    amount NUMERIC(15,2),
    transaction_date DATE,
    remarks VARCHAR(500),
    CONSTRAINT fk_bank_transactions_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_bank_transactions_bank_account FOREIGN KEY (bank_account_id) REFERENCES bank_accounts (id),
    CONSTRAINT fk_bank_transactions_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE TABLE IF NOT EXISTS cash_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    account_name VARCHAR(150),
    opening_balance NUMERIC(15,2),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_cash_accounts_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS cash_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    cash_account_id BIGINT,
    payment_id BIGINT,
    transaction_type VARCHAR(50),
    amount NUMERIC(15,2),
    transaction_date DATE,
    remarks VARCHAR(500),
    CONSTRAINT fk_cash_transactions_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_cash_transactions_cash_account FOREIGN KEY (cash_account_id) REFERENCES cash_accounts (id),
    CONSTRAINT fk_cash_transactions_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE TABLE IF NOT EXISTS expense_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_expense_categories_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS expense_sub_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    expense_category_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_expense_sub_categories_expense_category FOREIGN KEY (expense_category_id) REFERENCES expense_categories (id)
);

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    expense_no VARCHAR(50) NOT NULL,
    expense_category_id BIGINT,
    expense_date DATE,
    amount NUMERIC(15,2),
    payment_method_id BIGINT,
    notes VARCHAR(500),
    attachment_url VARCHAR(500),
    CONSTRAINT fk_expenses_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_expenses_expense_category FOREIGN KEY (expense_category_id) REFERENCES expense_categories (id),
    CONSTRAINT fk_expenses_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id)
);

CREATE TABLE IF NOT EXISTS sms_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    content TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_sms_templates_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    subject VARCHAR(200),
    content TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_email_templates_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    user_id BIGINT,
    module_name VARCHAR(100),
    record_id BIGINT,
    action VARCHAR(50),
    old_value TEXT,
    new_value TEXT,
    ip_address VARCHAR(50),
    CONSTRAINT fk_audit_logs_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_code VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20),
    dob DATE,
    mobile VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    address TEXT,
    department VARCHAR(100) NOT NULL,
    designation VARCHAR(100) NOT NULL,
    joining_date DATE NOT NULL,
    employment_type VARCHAR(30) NOT NULL,
    reporting_manager VARCHAR(150),
    basic_salary NUMERIC(14,2) DEFAULT 0,
    hra NUMERIC(14,2) DEFAULT 0,
    allowance NUMERIC(14,2) DEFAULT 0,
    deductions NUMERIC(14,2) DEFAULT 0,
    payment_mode VARCHAR(50),
    bank_name VARCHAR(150),
    account_number VARCHAR(50),
    ifsc_code VARCHAR(20),
    account_holder_name VARCHAR(150),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_employees_organization_employee_code UNIQUE (organization_id, employee_code),
    CONSTRAINT fk_employees_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS staff_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    check_in TIME,
    check_out TIME,
    total_hours NUMERIC(6,2) DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    note TEXT,
    CONSTRAINT uk_staff_attendance_organization_employee_date UNIQUE (organization_id, employee_id, attendance_date),
    CONSTRAINT fk_staff_attendance_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_staff_attendance_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS staff_leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    leave_type VARCHAR(100) NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    days NUMERIC(5,1) NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_by BIGINT,
    approved_at TIMESTAMP(6),
    CONSTRAINT fk_staff_leave_requests_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_staff_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS staff_payroll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    payroll_month VARCHAR(7) NOT NULL,
    basic_salary NUMERIC(14,2) DEFAULT 0,
    hra NUMERIC(14,2) DEFAULT 0,
    allowance NUMERIC(14,2) DEFAULT 0,
    overtime_amount NUMERIC(14,2) DEFAULT 0,
    deductions NUMERIC(14,2) DEFAULT 0,
    tax NUMERIC(14,2) DEFAULT 0,
    gross_pay NUMERIC(14,2) NOT NULL,
    net_pay NUMERIC(14,2) NOT NULL,
    payment_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'GENERATED',
    CONSTRAINT uk_staff_payroll_organization_employee_month UNIQUE (organization_id, employee_id, payroll_month),
    CONSTRAINT fk_staff_payroll_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_staff_payroll_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS staff_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_staff_settings_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS staff_employee_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    document_type VARCHAR(100) NOT NULL,
    file_name VARCHAR(150) NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    object_url VARCHAR(500) NOT NULL,
    content_type VARCHAR(150),
    file_size BIGINT,
    CONSTRAINT fk_staff_employee_documents_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_staff_employee_documents_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS stock_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    adjustment_no VARCHAR(50) NOT NULL,
    warehouse_id BIGINT,
    adjustment_date DATE,
    reason VARCHAR(500),
    CONSTRAINT fk_stock_adjustments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_adjustments_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id)
);

CREATE TABLE IF NOT EXISTS stock_adjustment_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    stock_adjustment_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    current_qty NUMERIC(15,3),
    actual_qty NUMERIC(15,3),
    difference_qty NUMERIC(15,3),
    CONSTRAINT fk_stock_adjustment_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_adjustment_items_adjustment FOREIGN KEY (stock_adjustment_id) REFERENCES stock_adjustments (id),
    CONSTRAINT fk_stock_adjustment_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_stock_adjustment_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS stock_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    transfer_no VARCHAR(50) NOT NULL,
    from_warehouse_id BIGINT,
    to_warehouse_id BIGINT,
    transfer_date DATE,
    notes VARCHAR(500),
    CONSTRAINT fk_stock_transfers_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_transfers_from_warehouse FOREIGN KEY (from_warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_stock_transfers_to_warehouse FOREIGN KEY (to_warehouse_id) REFERENCES warehouses (id)
);

CREATE TABLE IF NOT EXISTS stock_transfer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    stock_transfer_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    CONSTRAINT fk_stock_transfer_items_transfer FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfers (id),
    CONSTRAINT fk_stock_transfer_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_stock_transfer_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE INDEX IF NOT EXISTS idx_roles_organization_id ON roles (organization_id);
CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);
CREATE INDEX IF NOT EXISTS idx_users_organization_id ON users (organization_id);
CREATE INDEX IF NOT EXISTS idx_user_permission_mapping_user_id ON user_permission_mapping (user_id);
CREATE INDEX IF NOT EXISTS idx_user_permission_mapping_permission_id ON user_permission_mapping (permission_id);
CREATE INDEX IF NOT EXISTS idx_contacts_organization_id ON contacts (organization_id);
CREATE INDEX IF NOT EXISTS idx_brands_category_id ON brands (category_id);
CREATE INDEX IF NOT EXISTS idx_items_organization_id ON items (organization_id);
CREATE INDEX IF NOT EXISTS idx_item_prices_item_id ON item_prices (item_id);
CREATE INDEX IF NOT EXISTS idx_item_batches_item_id ON item_batches (item_id);
CREATE INDEX IF NOT EXISTS idx_stock_item_id ON stock (item_id);
CREATE INDEX IF NOT EXISTS idx_stock_item_warehouse_batch_id ON stock (item_id, warehouse_id, batch_id);
CREATE INDEX IF NOT EXISTS idx_shipping_carriers_organization_id ON shipping_carriers (organization_id);
CREATE INDEX IF NOT EXISTS idx_purchases_organization_id ON purchases (organization_id);
CREATE INDEX IF NOT EXISTS idx_sales_organization_id ON sales (organization_id);
CREATE INDEX IF NOT EXISTS idx_quotations_organization_id ON quotations (organization_id);
CREATE INDEX IF NOT EXISTS idx_quotations_customer_id ON quotations (customer_id);
CREATE INDEX IF NOT EXISTS idx_quotation_items_quotation_id ON quotation_items (quotation_id);
CREATE INDEX IF NOT EXISTS idx_payment_methods_organization_id ON payment_methods (organization_id);
CREATE INDEX IF NOT EXISTS idx_payments_organization_id ON payments (organization_id);
CREATE INDEX IF NOT EXISTS idx_expense_categories_organization_id ON expense_categories (organization_id);
CREATE INDEX IF NOT EXISTS idx_expense_sub_categories_expense_category_id ON expense_sub_categories (expense_category_id);
CREATE INDEX IF NOT EXISTS idx_expenses_organization_id ON expenses (organization_id);
CREATE INDEX IF NOT EXISTS idx_sms_templates_organization_id ON sms_templates (organization_id);
CREATE INDEX IF NOT EXISTS idx_sms_templates_org_name ON sms_templates (organization_id, lower(name));
CREATE INDEX IF NOT EXISTS idx_email_templates_organization_id ON email_templates (organization_id);
CREATE INDEX IF NOT EXISTS idx_email_templates_org_name ON email_templates (organization_id, lower(name));
CREATE INDEX IF NOT EXISTS idx_audit_logs_organization_id ON audit_logs (organization_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_organization_created_at ON audit_logs (organization_id, created_at);
CREATE INDEX IF NOT EXISTS idx_employees_organization_status ON employees (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_employees_department ON employees (organization_id, department);
CREATE INDEX IF NOT EXISTS idx_staff_attendance_date ON staff_attendance (organization_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_staff_leave_requests_employee ON staff_leave_requests (organization_id, employee_id);
CREATE INDEX IF NOT EXISTS idx_staff_leave_requests_status ON staff_leave_requests (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_staff_payroll_month ON staff_payroll (organization_id, payroll_month);
CREATE INDEX IF NOT EXISTS idx_staff_settings_type ON staff_settings (organization_id, type);
CREATE INDEX IF NOT EXISTS idx_staff_employee_documents_employee ON staff_employee_documents (organization_id, employee_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_items_transfer_id ON stock_transfer_items (stock_transfer_id);
