-- Flyway baseline schema for BillTop.
-- Hibernate is configured with ddl-auto=validate, so Flyway owns table creation.

CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    logo_url VARCHAR(500),
    address VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_organizations_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    organization_id BIGINT NOT NULL,
    CONSTRAINT uk_roles_name UNIQUE (name),
    CONSTRAINT fk_roles_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    group_name VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_permissions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    user_name VARCHAR(50) NOT NULL,
    email VARCHAR(150) NOT NULL,
    mobile_no VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    role_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_user_name UNIQUE (user_name),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS role_permission_mapping (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_mapping_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_role_permission_mapping_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    iso_code VARCHAR(10),
    currency_code VARCHAR(10),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    country_id BIGINT,
    state_name VARCHAR(100) NOT NULL,
    state_code VARCHAR(20),
    gst_code VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_states_country FOREIGN KEY (country_id) REFERENCES countries (id)
);

CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    contact_type VARCHAR(50),
    company_name VARCHAR(150),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(150),
    phone VARCHAR(20),
    mobile VARCHAR(20),
    whatsapp_no VARCHAR(20),
    gst_number VARCHAR(30),
    pan_number VARCHAR(20),
    credit_limit NUMERIC(15,2),
    opening_balance NUMERIC(15,2),
    opening_balance_type VARCHAR(20),
    is_wholesale BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_contacts_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS contact_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    contact_id BIGINT,
    address_type VARCHAR(50),
    address_line1 VARCHAR(250),
    address_line2 VARCHAR(250),
    city VARCHAR(100),
    state_id BIGINT,
    country_id BIGINT,
    pincode VARCHAR(20),
    CONSTRAINT fk_contact_addresses_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_contact_addresses_contact FOREIGN KEY (contact_id) REFERENCES contacts (id),
    CONSTRAINT fk_contact_addresses_state FOREIGN KEY (state_id) REFERENCES states (id),
    CONSTRAINT fk_contact_addresses_country FOREIGN KEY (country_id) REFERENCES countries (id)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_categories_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS sub_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    category_id BIGINT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_sub_categories_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sub_categories_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_brands_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    short_name VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_units_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    item_name VARCHAR(150) NOT NULL,
    item_code VARCHAR(50),
    sku VARCHAR(80),
    barcode VARCHAR(80),
    hsn_code VARCHAR(30),
    category_id BIGINT,
    sub_category_id BIGINT,
    brand_id BIGINT,
    base_unit_id BIGINT,
    secondary_unit_id BIGINT,
    conversion_rate NUMERIC(15,4),
    description VARCHAR(500),
    image_url VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_items_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_items_sub_category FOREIGN KEY (sub_category_id) REFERENCES sub_categories (id),
    CONSTRAINT fk_items_brand FOREIGN KEY (brand_id) REFERENCES brands (id),
    CONSTRAINT fk_items_base_unit FOREIGN KEY (base_unit_id) REFERENCES units (id),
    CONSTRAINT fk_items_secondary_unit FOREIGN KEY (secondary_unit_id) REFERENCES units (id)
);

CREATE TABLE IF NOT EXISTS item_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    item_id BIGINT,
    purchase_price NUMERIC(15,2),
    purchase_price_with_tax NUMERIC(15,2),
    tax_percentage NUMERIC(5,2),
    sale_price NUMERIC(15,2),
    wholesale_price NUMERIC(15,2),
    mrp NUMERIC(15,2),
    msp NUMERIC(15,2),
    discount_percentage NUMERIC(5,2),
    profit_margin NUMERIC(5,2),
    effective_from DATE,
    CONSTRAINT fk_item_prices_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_item_prices_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS item_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    item_id BIGINT,
    batch_no VARCHAR(80),
    manufacturing_date DATE,
    expiry_date DATE,
    CONSTRAINT fk_item_batches_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_item_batches_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    warehouse_code VARCHAR(50),
    description VARCHAR(500),
    address VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_warehouses_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    item_id BIGINT,
    warehouse_id BIGINT,
    batch_id BIGINT,
    available_qty NUMERIC(15,3),
    reserved_qty NUMERIC(15,3),
    minimum_stock NUMERIC(15,3),
    reorder_level NUMERIC(15,3),
    rack_location VARCHAR(100),
    CONSTRAINT fk_stock_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_stock_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_stock_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS stock_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    item_id BIGINT,
    warehouse_id BIGINT,
    batch_id BIGINT,
    transaction_type VARCHAR(50),
    reference_id BIGINT,
    qty_in NUMERIC(15,3),
    qty_out NUMERIC(15,3),
    balance_qty NUMERIC(15,3),
    transaction_date TIMESTAMP(6),
    remarks VARCHAR(500),
    CONSTRAINT fk_stock_transactions_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_transactions_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_stock_transactions_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_stock_transactions_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS shipping_carriers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150),
    mobile VARCHAR(20),
    address VARCHAR(500),
    note VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    purchase_no VARCHAR(50) NOT NULL,
    supplier_id BIGINT,
    purchase_date DATE,
    reference_no VARCHAR(100),
    warehouse_id BIGINT,
    carrier_id BIGINT,
    state_id BIGINT,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    round_off NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    paid_amount NUMERIC(15,2),
    due_amount NUMERIC(15,2),
    status VARCHAR(50),
    notes VARCHAR(500),
    CONSTRAINT fk_purchases_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchases_supplier FOREIGN KEY (supplier_id) REFERENCES contacts (id),
    CONSTRAINT fk_purchases_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_purchases_carrier FOREIGN KEY (carrier_id) REFERENCES shipping_carriers (id),
    CONSTRAINT fk_purchases_state FOREIGN KEY (state_id) REFERENCES states (id)
);

CREATE TABLE IF NOT EXISTS purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    purchase_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    unit_price NUMERIC(15,2),
    discount_percent NUMERIC(5,2),
    discount_amount NUMERIC(15,2),
    tax_percent NUMERIC(5,2),
    tax_amount NUMERIC(15,2),
    total_amount NUMERIC(15,2),
    CONSTRAINT fk_purchase_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchase_items_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_purchase_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_purchase_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS purchase_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    return_no VARCHAR(50) NOT NULL,
    purchase_id BIGINT,
    supplier_id BIGINT,
    return_date DATE,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    notes VARCHAR(500),
    CONSTRAINT fk_purchase_returns_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchase_returns_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_purchase_returns_supplier FOREIGN KEY (supplier_id) REFERENCES contacts (id)
);

CREATE TABLE IF NOT EXISTS purchase_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    purchase_return_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    rate NUMERIC(15,2),
    amount NUMERIC(15,2),
    CONSTRAINT fk_purchase_return_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchase_return_items_return FOREIGN KEY (purchase_return_id) REFERENCES purchase_returns (id),
    CONSTRAINT fk_purchase_return_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_purchase_return_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    invoice_no VARCHAR(50) NOT NULL,
    invoice_date DATE,
    customer_id BIGINT,
    warehouse_id BIGINT,
    state_id BIGINT,
    sales_person_id BIGINT,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    round_off NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    paid_amount NUMERIC(15,2),
    due_amount NUMERIC(15,2),
    status VARCHAR(50),
    notes VARCHAR(500),
    CONSTRAINT fk_sales_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES contacts (id),
    CONSTRAINT fk_sales_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_sales_state FOREIGN KEY (state_id) REFERENCES states (id),
    CONSTRAINT fk_sales_sales_person FOREIGN KEY (sales_person_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS sales_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    sale_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    unit_price NUMERIC(15,2),
    discount_percent NUMERIC(5,2),
    discount_amount NUMERIC(15,2),
    tax_percent NUMERIC(5,2),
    tax_amount NUMERIC(15,2),
    total_amount NUMERIC(15,2),
    CONSTRAINT fk_sales_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_items_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_sales_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_sales_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS sales_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    return_no VARCHAR(50) NOT NULL,
    sale_id BIGINT,
    customer_id BIGINT,
    return_date DATE,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    notes VARCHAR(500),
    CONSTRAINT fk_sales_returns_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_returns_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_sales_returns_customer FOREIGN KEY (customer_id) REFERENCES contacts (id)
);

CREATE TABLE IF NOT EXISTS sales_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    sales_return_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    rate NUMERIC(15,2),
    amount NUMERIC(15,2),
    CONSTRAINT fk_sales_return_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_return_items_return FOREIGN KEY (sales_return_id) REFERENCES sales_returns (id),
    CONSTRAINT fk_sales_return_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_sales_return_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    payment_no VARCHAR(50) NOT NULL,
    payment_type VARCHAR(50),
    payment_method_id BIGINT,
    contact_id BIGINT,
    amount NUMERIC(15,2),
    payment_date DATE,
    reference_no VARCHAR(100),
    notes VARCHAR(500),
    CONSTRAINT fk_payments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_payments_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id),
    CONSTRAINT fk_payments_contact FOREIGN KEY (contact_id) REFERENCES contacts (id)
);

CREATE TABLE IF NOT EXISTS sales_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    sale_id BIGINT,
    payment_id BIGINT,
    amount NUMERIC(15,2),
    CONSTRAINT fk_sales_payments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_sales_payments_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_sales_payments_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE TABLE IF NOT EXISTS purchase_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    purchase_id BIGINT,
    payment_id BIGINT,
    amount NUMERIC(15,2),
    CONSTRAINT fk_purchase_payments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_purchase_payments_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT fk_purchase_payments_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE TABLE IF NOT EXISTS bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    bank_name VARCHAR(150),
    account_name VARCHAR(150),
    account_number VARCHAR(50),
    ifsc_code VARCHAR(20),
    branch_name VARCHAR(150),
    opening_balance NUMERIC(15,2),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_bank_accounts_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS bank_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    bank_account_id BIGINT,
    payment_id BIGINT,
    transaction_type VARCHAR(50),
    amount NUMERIC(15,2),
    transaction_date DATE,
    remarks VARCHAR(500),
    CONSTRAINT fk_bank_transactions_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_bank_transactions_bank_account FOREIGN KEY (bank_account_id) REFERENCES bank_accounts (id),
    CONSTRAINT fk_bank_transactions_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE TABLE IF NOT EXISTS cash_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    account_name VARCHAR(150),
    opening_balance NUMERIC(15,2),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_cash_accounts_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS cash_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    cash_account_id BIGINT,
    payment_id BIGINT,
    transaction_type VARCHAR(50),
    amount NUMERIC(15,2),
    transaction_date DATE,
    remarks VARCHAR(500),
    CONSTRAINT fk_cash_transactions_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_cash_transactions_cash_account FOREIGN KEY (cash_account_id) REFERENCES cash_accounts (id),
    CONSTRAINT fk_cash_transactions_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE TABLE IF NOT EXISTS expense_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    expense_no VARCHAR(50) NOT NULL,
    expense_category_id BIGINT,
    expense_date DATE,
    amount NUMERIC(15,2),
    payment_method_id BIGINT,
    notes VARCHAR(500),
    attachment_url VARCHAR(500),
    CONSTRAINT fk_expenses_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_expenses_expense_category FOREIGN KEY (expense_category_id) REFERENCES expense_categories (id),
    CONSTRAINT fk_expenses_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id)
);

CREATE TABLE IF NOT EXISTS sms_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    content TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    subject VARCHAR(200),
    content TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT,
    module_name VARCHAR(100),
    record_id BIGINT,
    action VARCHAR(50),
    old_value TEXT,
    new_value TEXT,
    ip_address VARCHAR(50),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS stock_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    adjustment_no VARCHAR(50) NOT NULL,
    warehouse_id BIGINT,
    adjustment_date DATE,
    reason VARCHAR(500),
    CONSTRAINT fk_stock_adjustments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_adjustments_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id)
);

CREATE TABLE IF NOT EXISTS stock_adjustment_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    stock_adjustment_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    current_qty NUMERIC(15,3),
    actual_qty NUMERIC(15,3),
    difference_qty NUMERIC(15,3),
    CONSTRAINT fk_stock_adjustment_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_adjustment_items_adjustment FOREIGN KEY (stock_adjustment_id) REFERENCES stock_adjustments (id),
    CONSTRAINT fk_stock_adjustment_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_stock_adjustment_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE TABLE IF NOT EXISTS stock_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    transfer_no VARCHAR(50) NOT NULL,
    from_warehouse_id BIGINT,
    to_warehouse_id BIGINT,
    transfer_date DATE,
    notes VARCHAR(500),
    CONSTRAINT fk_stock_transfers_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_transfers_from_warehouse FOREIGN KEY (from_warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_stock_transfers_to_warehouse FOREIGN KEY (to_warehouse_id) REFERENCES warehouses (id)
);

CREATE TABLE IF NOT EXISTS stock_transfer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    stock_transfer_id BIGINT,
    item_id BIGINT,
    batch_id BIGINT,
    qty NUMERIC(15,3),
    CONSTRAINT fk_stock_transfer_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_stock_transfer_items_transfer FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfers (id),
    CONSTRAINT fk_stock_transfer_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_stock_transfer_items_batch FOREIGN KEY (batch_id) REFERENCES item_batches (id)
);

CREATE INDEX IF NOT EXISTS idx_roles_organization_id ON roles (organization_id);
CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);
CREATE INDEX IF NOT EXISTS idx_users_organization_id ON users (organization_id);
CREATE INDEX IF NOT EXISTS idx_contacts_organization_id ON contacts (organization_id);
CREATE INDEX IF NOT EXISTS idx_items_organization_id ON items (organization_id);
CREATE INDEX IF NOT EXISTS idx_stock_organization_id ON stock (organization_id);
CREATE INDEX IF NOT EXISTS idx_purchases_organization_id ON purchases (organization_id);
CREATE INDEX IF NOT EXISTS idx_sales_organization_id ON sales (organization_id);
CREATE INDEX IF NOT EXISTS idx_payments_organization_id ON payments (organization_id);
CREATE INDEX IF NOT EXISTS idx_expenses_organization_id ON expenses (organization_id);
