-- Branch management: organizations can have multiple branches; users are
-- assigned to one or more branches; branch-scoped master data references branches.

CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    branch_code VARCHAR(50) NOT NULL,
    branch_name VARCHAR(150) NOT NULL,
    email VARCHAR(150),
    phone VARCHAR(20),
    address VARCHAR(500),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    pincode VARCHAR(20),
    gst_number VARCHAR(30),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_branches_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT uk_branches_org_code UNIQUE (organization_id, branch_code)
);

CREATE TABLE IF NOT EXISTS user_branch_mapping (
    user_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, branch_id),
    CONSTRAINT fk_user_branch_mapping_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_branch_mapping_branch FOREIGN KEY (branch_id) REFERENCES branches (id)
);

-- Backfill: one Main Branch per existing organization so branch_id can be
-- required going forward without breaking existing data.
INSERT INTO branches (created_by, organization_id, branch_code, branch_name, is_active)
SELECT 'SYSTEM', o.id, 'MAIN', 'Main Branch', TRUE
FROM organizations o;

-- Map every existing org-scoped user to their organization's Main Branch.
INSERT INTO user_branch_mapping (user_id, branch_id)
SELECT u.id, b.id
FROM users u
JOIN branches b ON b.organization_id = u.organization_id AND b.branch_code = 'MAIN'
WHERE u.organization_id IS NOT NULL;

-- Pilot rollout: warehouses become branch-scoped.
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS branch_id BIGINT;
UPDATE warehouses w
SET branch_id = (SELECT b.id FROM branches b WHERE b.organization_id = w.organization_id AND b.branch_code = 'MAIN')
WHERE branch_id IS NULL;
ALTER TABLE warehouses ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE warehouses ADD CONSTRAINT fk_warehouses_branch FOREIGN KEY (branch_id) REFERENCES branches (id);

-- Pilot rollout: contacts (customers/suppliers) become branch-scoped.
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS branch_id BIGINT;
UPDATE contacts c
SET branch_id = (SELECT b.id FROM branches b WHERE b.organization_id = c.organization_id AND b.branch_code = 'MAIN')
WHERE branch_id IS NULL;
ALTER TABLE contacts ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE contacts ADD CONSTRAINT fk_contacts_branch FOREIGN KEY (branch_id) REFERENCES branches (id);
