CREATE TABLE IF NOT EXISTS quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    quotation_no VARCHAR(50) NOT NULL,
    quotation_date DATE,
    valid_until DATE,
    customer_id BIGINT,
    warehouse_id BIGINT,
    state_id BIGINT,
    sales_person_id BIGINT,
    converted_sale_id BIGINT,
    sub_total NUMERIC(15,2),
    discount_amount NUMERIC(15,2),
    tax_amount NUMERIC(15,2),
    round_off NUMERIC(15,2),
    grand_total NUMERIC(15,2),
    status VARCHAR(50),
    notes VARCHAR(500),
    CONSTRAINT fk_quotations_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_quotations_customer FOREIGN KEY (customer_id) REFERENCES contacts (id),
    CONSTRAINT fk_quotations_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT fk_quotations_state FOREIGN KEY (state_id) REFERENCES states (id),
    CONSTRAINT fk_quotations_sales_person FOREIGN KEY (sales_person_id) REFERENCES users (id),
    CONSTRAINT fk_quotations_converted_sale FOREIGN KEY (converted_sale_id) REFERENCES sales (id)
);

CREATE TABLE IF NOT EXISTS quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    quotation_id BIGINT,
    item_id BIGINT,
    qty NUMERIC(15,3),
    unit_price NUMERIC(15,2),
    discount_percent NUMERIC(5,2),
    discount_amount NUMERIC(15,2),
    tax_percent NUMERIC(5,2),
    tax_amount NUMERIC(15,2),
    total_amount NUMERIC(15,2),
    CONSTRAINT fk_quotation_items_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_quotation_items_quotation FOREIGN KEY (quotation_id) REFERENCES quotations (id),
    CONSTRAINT fk_quotation_items_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE INDEX IF NOT EXISTS idx_quotations_organization_id ON quotations (organization_id);
CREATE INDEX IF NOT EXISTS idx_quotations_customer_id ON quotations (customer_id);
CREATE INDEX IF NOT EXISTS idx_quotation_items_quotation_id ON quotation_items (quotation_id);
