CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_code VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20),
    dob DATE,
    mobile VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    address TEXT,
    department VARCHAR(100) NOT NULL,
    designation VARCHAR(100) NOT NULL,
    joining_date DATE NOT NULL,
    employment_type VARCHAR(30) NOT NULL,
    reporting_manager VARCHAR(150),
    basic_salary NUMERIC(14,2) DEFAULT 0,
    hra NUMERIC(14,2) DEFAULT 0,
    allowance NUMERIC(14,2) DEFAULT 0,
    deductions NUMERIC(14,2) DEFAULT 0,
    payment_mode VARCHAR(50),
    bank_name VARCHAR(150),
    account_number VARCHAR(50),
    ifsc_code VARCHAR(20),
    account_holder_name VARCHAR(150),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_employees_organization_employee_code UNIQUE (organization_id, employee_code),
    CONSTRAINT fk_employees_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS staff_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    check_in TIME,
    check_out TIME,
    total_hours NUMERIC(6,2) DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    note TEXT,
    CONSTRAINT uk_staff_attendance_organization_employee_date UNIQUE (organization_id, employee_id, attendance_date),
    CONSTRAINT fk_staff_attendance_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_staff_attendance_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS staff_leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    leave_type VARCHAR(100) NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    days NUMERIC(5,1) NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_by BIGINT,
    approved_at TIMESTAMP(6),
    CONSTRAINT fk_staff_leave_requests_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_staff_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS staff_payroll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    payroll_month VARCHAR(7) NOT NULL,
    basic_salary NUMERIC(14,2) DEFAULT 0,
    hra NUMERIC(14,2) DEFAULT 0,
    allowance NUMERIC(14,2) DEFAULT 0,
    overtime_amount NUMERIC(14,2) DEFAULT 0,
    deductions NUMERIC(14,2) DEFAULT 0,
    tax NUMERIC(14,2) DEFAULT 0,
    gross_pay NUMERIC(14,2) NOT NULL,
    net_pay NUMERIC(14,2) NOT NULL,
    payment_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'GENERATED',
    CONSTRAINT uk_staff_payroll_organization_employee_month UNIQUE (organization_id, employee_id, payroll_month),
    CONSTRAINT fk_staff_payroll_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_staff_payroll_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS staff_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_staff_settings_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS staff_employee_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    document_type VARCHAR(100) NOT NULL,
    file_name VARCHAR(150) NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    object_url VARCHAR(500) NOT NULL,
    content_type VARCHAR(150),
    file_size BIGINT,
    CONSTRAINT fk_staff_employee_documents_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_staff_employee_documents_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE INDEX IF NOT EXISTS idx_employees_organization_status ON employees (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_employees_department ON employees (organization_id, department);
CREATE INDEX IF NOT EXISTS idx_staff_attendance_date ON staff_attendance (organization_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_staff_leave_requests_employee ON staff_leave_requests (organization_id, employee_id);
CREATE INDEX IF NOT EXISTS idx_staff_leave_requests_status ON staff_leave_requests (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_staff_payroll_month ON staff_payroll (organization_id, payroll_month);
CREATE INDEX IF NOT EXISTS idx_staff_settings_type ON staff_settings (organization_id, type);
CREATE INDEX IF NOT EXISTS idx_staff_employee_documents_employee ON staff_employee_documents (organization_id, employee_id);
