-- Payment Note: ServiceNow-style ticket used to track post-invoice discount
-- negotiations and pending/unpaid customer balances, with its own audit trail.

CREATE TABLE IF NOT EXISTS payment_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    note_no VARCHAR(50) NOT NULL,
    contact_id BIGINT NOT NULL,
    sale_id BIGINT,
    payment_id BIGINT,
    note_type VARCHAR(50) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    description TEXT,
    amount NUMERIC(15,2),
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    assigned_to BIGINT,
    resolution_notes TEXT,
    resolved_at TIMESTAMP(6),
    CONSTRAINT fk_payment_notes_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_payment_notes_contact FOREIGN KEY (contact_id) REFERENCES contacts (id),
    CONSTRAINT fk_payment_notes_sale FOREIGN KEY (sale_id) REFERENCES sales (id),
    CONSTRAINT fk_payment_notes_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT fk_payment_notes_assigned_to FOREIGN KEY (assigned_to) REFERENCES users (id),
    CONSTRAINT uk_payment_notes_org_note_no UNIQUE (organization_id, note_no)
);

CREATE INDEX IF NOT EXISTS idx_payment_notes_organization ON payment_notes (organization_id);
CREATE INDEX IF NOT EXISTS idx_payment_notes_contact ON payment_notes (contact_id);
CREATE INDEX IF NOT EXISTS idx_payment_notes_status ON payment_notes (status);

CREATE TABLE IF NOT EXISTS payment_note_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    updated_by VARCHAR(255),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    organization_id BIGINT NOT NULL,
    payment_note_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    field_name VARCHAR(50),
    old_value TEXT,
    new_value TEXT,
    CONSTRAINT fk_payment_note_audits_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_payment_note_audits_payment_note FOREIGN KEY (payment_note_id) REFERENCES payment_notes (id)
);

CREATE INDEX IF NOT EXISTS idx_payment_note_audits_payment_note ON payment_note_audits (payment_note_id);
