export const DEFAULT_LEAVE_TYPES = [
  {
    name: 'Casual Leave',
    code: 'CL',
    daysPerYear: 12,
    canCarryForward: false,
    maxCarryForwardDays: 0,
    isGenderSpecific: false,
    minServiceMonths: 0,
    requiresDocument: false,
    documentRequiredAfterDays: 0,
    expiryDays: 0,
    isPaidLeave: true,
  },
  {
    name: 'Sick Leave',
    code: 'SL',
    daysPerYear: 12,
    canCarryForward: false,
    maxCarryForwardDays: 0,
    isGenderSpecific: false,
    minServiceMonths: 0,
    requiresDocument: true,
    documentRequiredAfterDays: 2,
    expiryDays: 0,
    isPaidLeave: true,
  },
  {
    name: 'Earned Leave',
    code: 'EL',
    daysPerYear: 15,
    canCarryForward: true,
    maxCarryForwardDays: 30,
    isGenderSpecific: false,
    minServiceMonths: 0,
    requiresDocument: false,
    documentRequiredAfterDays: 0,
    expiryDays: 0,
    isPaidLeave: true,
  },
  {
    name: 'Maternity Leave',
    code: 'ML',
    daysPerYear: 182, // 26 weeks
    canCarryForward: false,
    maxCarryForwardDays: 0,
    isGenderSpecific: true,
    genderAllowed: 'FEMALE' as const,
    minServiceMonths: 6,
    requiresDocument: true,
    documentRequiredAfterDays: 0,
    expiryDays: 0,
    isPaidLeave: true,
  },
  {
    name: 'Paternity Leave',
    code: 'PL',
    daysPerYear: 15,
    canCarryForward: false,
    maxCarryForwardDays: 0,
    isGenderSpecific: true,
    genderAllowed: 'MALE' as const,
    minServiceMonths: 0,
    requiresDocument: false,
    documentRequiredAfterDays: 0,
    expiryDays: 0,
    isPaidLeave: true,
  },
  {
    name: 'Compensatory Off',
    code: 'CO',
    daysPerYear: 0,
    canCarryForward: false,
    maxCarryForwardDays: 0,
    isGenderSpecific: false,
    minServiceMonths: 0,
    requiresDocument: false,
    documentRequiredAfterDays: 0,
    expiryDays: 30,
    isPaidLeave: true,
  },
];
