import React, { useState } from 'react';
import { Pagination } from '../../components/ui/Pagination';
import { usePagination } from '../../hooks/usePagination';

export const ChequesPage: React.FC = () => {
  const { page, handlePageChange } = usePagination();
  const [pageSize, setPageSize] = useState(10);
  return <div className="space-y-5"><div className="text-sm text-gray-500">Home &gt; Cash &amp; Bank &gt; Cheques</div><div className="overflow-hidden rounded-lg bg-white shadow"><div className="border-b px-5 py-4"><h1 className="text-xl font-semibold uppercase">Cheques</h1></div><div className="grid grid-cols-1 gap-4 p-5 md:grid-cols-2"><label className="text-sm">From Date<input type="date" className="mt-1 h-10 w-full rounded border px-3" /></label><label className="text-sm">To Date<input type="date" className="mt-1 h-10 w-full rounded border px-3" /></label></div><div className="flex flex-wrap items-center justify-between gap-3 px-5 pb-4"><label className="flex items-center gap-2 text-sm">Show<select value={pageSize} onChange={(event) => setPageSize(Number(event.target.value))} className="h-9 rounded border px-2"><option>10</option><option>20</option></select>entries</label><div className="flex"><button className="h-10 rounded-l border border-red-300 px-3 text-sm text-red-500">Delete</button><button className="h-10 border-y border-r px-3 text-sm">Copy</button><button className="h-10 border-y border-r px-3 text-sm">Excel</button><button className="h-10 border-y border-r px-3 text-sm">CSV</button><button className="h-10 rounded-r border-y border-r px-3 text-sm">PDF</button></div><label className="flex items-center gap-2 text-sm">Search:<input className="h-9 rounded border px-3" /></label></div><div className="overflow-x-auto px-3 pb-3"><table className="w-full text-sm"><thead className="bg-gray-50"><tr>{['Type', 'Date', 'Party Name', 'Amount', 'Deposit Date', 'Status', 'Created by', 'Action'].map((heading) => <th key={heading} className="border p-3 text-left">{heading}</th>)}</tr></thead><tbody><tr><td colSpan={8} className="bg-gray-50 p-5 text-center">No data available in table</td></tr></tbody></table></div><div className="flex items-center justify-between border-t px-5 py-4 text-sm text-gray-600"><span>Showing 0 to 0 of 0 entries</span><Pagination page={page} totalPages={1} onPageChange={handlePageChange} /></div></div></div>;
};
