{{- $global := .Values.global }}
{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $global.namespace }}
  labels:
    app: {{ $name }}
---
{{- end }}
