-- Phase ES-04: Missing tables for production-service and report-service (Phase 10/11 schema gap)
-- Generated: 2026-07-02
-- DO NOT EDIT THIS FILE

-- ─── Job Work Orders ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "job_work_orders" (
  "id" BIGSERIAL PRIMARY KEY,
  "tenant_id" INTEGER NOT NULL,
  "order_number" VARCHAR(50),
  "status" VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  "supplier_id" INTEGER NOT NULL,
  "branch_id" INTEGER NOT NULL,
  "warehouse_id" INTEGER NOT NULL,
  "output_item_id" INTEGER NOT NULL,
  "output_variant_id" INTEGER,
  "ordered_qty" NUMERIC(15, 3) NOT NULL,
  "received_qty" NUMERIC(15, 3) NOT NULL DEFAULT '0',
  "rejected_qty" NUMERIC(15, 3) NOT NULL DEFAULT '0',
  "scrap_qty" NUMERIC(15, 3) NOT NULL DEFAULT '0',
  "job_work_rate" NUMERIC(15, 2) NOT NULL DEFAULT '0',
  "job_work_charges" NUMERIC(15, 2) NOT NULL DEFAULT '0',
  "materials_cost" NUMERIC(15, 2) NOT NULL DEFAULT '0',
  "finished_goods_cost" NUMERIC(15, 2) NOT NULL DEFAULT '0',
  "order_date" TIMESTAMPTZ NOT NULL,
  "expected_date" TIMESTAMPTZ,
  "issued_at" TIMESTAMPTZ,
  "completed_at" TIMESTAMPTZ,
  "cancelled_at" TIMESTAMPTZ,
  "cancellation_reason" TEXT,
  "notes" TEXT,
  "created_by" INTEGER NOT NULL,
  "updated_by" INTEGER,
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS "idx_job_work_orders_tenant" ON "job_work_orders" ("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "idx_job_work_orders_supplier" ON "job_work_orders" ("supplier_id", "tenant_id");
CREATE INDEX IF NOT EXISTS "idx_job_work_orders_item" ON "job_work_orders" ("output_item_id", "tenant_id");
CREATE INDEX IF NOT EXISTS "idx_job_work_orders_date" ON "job_work_orders" ("tenant_id", "order_date");

-- ─── Job Work Order Materials (Raw Material Inputs) ───────────────────────────
CREATE TABLE IF NOT EXISTS "job_work_order_materials" (
  "id" BIGSERIAL PRIMARY KEY,
  "job_work_order_id" INTEGER NOT NULL,
  "tenant_id" INTEGER NOT NULL,
  "item_id" INTEGER NOT NULL,
  "variant_id" INTEGER,
  "required_qty" NUMERIC(15, 3) NOT NULL,
  "issued_qty" NUMERIC(15, 3) NOT NULL DEFAULT '0',
  "unit_cost" NUMERIC(15, 2) NOT NULL DEFAULT '0',
  "total_cost" NUMERIC(15, 2) NOT NULL DEFAULT '0',
  "warehouse_id" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_jwom_order" ON "job_work_order_materials" ("job_work_order_id");
CREATE INDEX IF NOT EXISTS "idx_jwom_tenant_item" ON "job_work_order_materials" ("tenant_id", "item_id");

-- ─── Job Work Order Quality Checks ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "job_work_order_quality_checks" (
  "id" BIGSERIAL PRIMARY KEY,
  "job_work_order_id" INTEGER NOT NULL,
  "tenant_id" INTEGER NOT NULL,
  "piece_number" INTEGER NOT NULL,
  "result" VARCHAR(20) NOT NULL,
  "defect_notes" TEXT,
  "inspected_by" INTEGER NOT NULL,
  "inspected_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_jwqc_order" ON "job_work_order_quality_checks" ("job_work_order_id", "tenant_id");

-- ─── Job Work Order History ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "job_work_order_history" (
  "id" BIGSERIAL PRIMARY KEY,
  "job_work_order_id" INTEGER NOT NULL,
  "tenant_id" INTEGER NOT NULL,
  "action" VARCHAR(100) NOT NULL,
  "from_status" VARCHAR(30),
  "to_status" VARCHAR(30),
  "performed_by" INTEGER NOT NULL,
  "notes" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_jwo_history_order" ON "job_work_order_history" ("job_work_order_id", "tenant_id");

-- ─── Barcode Batches (Print Sessions) ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "barcode_batches" (
  "id" BIGSERIAL PRIMARY KEY,
  "tenant_id" INTEGER NOT NULL,
  "item_id" INTEGER NOT NULL,
  "variant_id" INTEGER,
  "quantity" INTEGER NOT NULL,
  "format" VARCHAR(20) NOT NULL DEFAULT 'EAN13',
  "print_format" VARCHAR(30) NOT NULL DEFAULT 'LABEL_40x25',
  "print_url" TEXT,
  "created_by" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_barcode_batches_tenant" ON "barcode_batches" ("tenant_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_barcode_batches_item" ON "barcode_batches" ("item_id", "tenant_id");

-- ─── Barcodes (Individual Barcode Records) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS "barcodes" (
  "id" BIGSERIAL PRIMARY KEY,
  "tenant_id" INTEGER NOT NULL,
  "batch_id" INTEGER NOT NULL,
  "item_id" INTEGER NOT NULL,
  "variant_id" INTEGER,
  "barcode_value" VARCHAR(200) NOT NULL,
  "format" VARCHAR(20) NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "deactivated_at" TIMESTAMPTZ,
  "deactivated_by" INTEGER,
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "barcodes_tenant_value" ON "barcodes" ("tenant_id", "barcode_value");
CREATE INDEX IF NOT EXISTS "idx_barcodes_item" ON "barcodes" ("item_id", "tenant_id");
CREATE INDEX IF NOT EXISTS "idx_barcodes_value" ON "barcodes" ("barcode_value", "tenant_id");
CREATE INDEX IF NOT EXISTS "idx_barcodes_batch" ON "barcodes" ("batch_id");

-- ─── Consignment Stocks ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "consignment_stocks" (
  "id" BIGSERIAL PRIMARY KEY,
  "tenant_id" INTEGER NOT NULL,
  "supplier_id" INTEGER NOT NULL,
  "item_id" INTEGER NOT NULL,
  "variant_id" INTEGER,
  "warehouse_id" INTEGER NOT NULL,
  "received_qty" NUMERIC(15, 3) NOT NULL,
  "sold_qty" NUMERIC(15, 3) NOT NULL DEFAULT '0',
  "returned_qty" NUMERIC(15, 3) NOT NULL DEFAULT '0',
  "available_qty" NUMERIC(15, 3) NOT NULL,
  "agreed_rate" NUMERIC(15, 2) NOT NULL,
  "received_date" TIMESTAMPTZ NOT NULL,
  "reference_number" VARCHAR(100),
  "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  "notes" TEXT,
  "created_by" INTEGER NOT NULL,
  "updated_by" INTEGER,
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS "idx_consignment_stocks_tenant" ON "consignment_stocks" ("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "idx_consignment_stocks_supplier" ON "consignment_stocks" ("supplier_id", "tenant_id");
CREATE INDEX IF NOT EXISTS "idx_consignment_stocks_item" ON "consignment_stocks" ("item_id", "tenant_id");

-- ─── Consignment Settlements ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "consignment_settlements" (
  "id" BIGSERIAL PRIMARY KEY,
  "tenant_id" INTEGER NOT NULL,
  "supplier_id" INTEGER NOT NULL,
  "settlement_number" VARCHAR(50),
  "period_from" TIMESTAMPTZ NOT NULL,
  "period_to" TIMESTAMPTZ NOT NULL,
  "total_sold_qty" NUMERIC(15, 3) NOT NULL DEFAULT '0',
  "total_amount" NUMERIC(15, 2) NOT NULL DEFAULT '0',
  "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  "settled_at" TIMESTAMPTZ,
  "settled_by" INTEGER,
  "payment_reference" VARCHAR(100),
  "line_items" JSONB NOT NULL DEFAULT '[]',
  "notes" TEXT,
  "created_by" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_consignment_settlements_tenant" ON "consignment_settlements" ("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "idx_consignment_settlements_supplier" ON "consignment_settlements" ("supplier_id", "tenant_id");

-- ─── Report Schedules ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "report_schedules" (
  "id" BIGSERIAL PRIMARY KEY,
  "tenant_id" INTEGER NOT NULL,
  "report_slug" VARCHAR(100) NOT NULL,
  "params" JSONB NOT NULL DEFAULT '{}',
  "format" VARCHAR(10) NOT NULL DEFAULT 'PDF',
  "cron_expression" VARCHAR(100) NOT NULL,
  "recipients" JSONB NOT NULL DEFAULT '[]',
  "active" INTEGER NOT NULL DEFAULT 1,
  "unsubscribe_token" VARCHAR(64) NOT NULL,
  "created_by" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_report_schedules_tenant" ON "report_schedules" ("tenant_id", "active");

-- ─── Report Run History ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "report_run_history" (
  "id" BIGSERIAL PRIMARY KEY,
  "tenant_id" INTEGER NOT NULL,
  "schedule_id" INTEGER,
  "report_slug" VARCHAR(100) NOT NULL,
  "params" JSONB NOT NULL DEFAULT '{}',
  "format" VARCHAR(10) NOT NULL DEFAULT 'PDF',
  "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  "started_at" TIMESTAMPTZ,
  "completed_at" TIMESTAMPTZ,
  "file_url" TEXT,
  "error_message" TEXT,
  "triggered_by" VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
  "row_count" INTEGER,
  "duration_ms" INTEGER,
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_report_run_tenant" ON "report_run_history" ("tenant_id", "status");
CREATE INDEX IF NOT EXISTS "idx_report_run_schedule" ON "report_run_history" ("schedule_id");
