export interface ReportColumnDef {
  key: string;
  label: string;
  type: 'string' | 'number' | 'currency' | 'date' | 'percent';
  align?: 'left' | 'right' | 'center';
}

export interface ReportParamDef {
  key: string;
  label: string;
  type: 'date' | 'daterange' | 'select' | 'text' | 'number' | 'multiselect';
  required: boolean;
  options?: { value: string; label: string }[];
  default?: string;
}

export interface ReportDefinition {
  slug: string;
  name: string;
  category: 'SALES' | 'PURCHASE' | 'INVENTORY' | 'FINANCIAL' | 'HR' | 'GST';
  description: string;
  params: ReportParamDef[];
  columns: ReportColumnDef[];
  permission: string;
  supportsAsync: boolean;
}

export const REPORT_REGISTRY: ReportDefinition[] = [
  // ── SALES REPORTS ──
  {
    slug: 'sales-register',
    name: 'Sales Register',
    category: 'SALES',
    description: 'All sales invoices with customer, amount, GST and payment status',
    permission: 'INVOICE_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'branchId', label: 'Branch', type: 'select', required: false },
      { key: 'status', label: 'Status', type: 'select', required: false, options: [{ value: 'PAID', label: 'Paid' }, { value: 'UNPAID', label: 'Unpaid' }, { value: 'CANCELLED', label: 'Cancelled' }] },
    ],
    columns: [
      { key: 'invoiceNumber', label: 'Invoice No', type: 'string' },
      { key: 'invoiceDate', label: 'Date', type: 'date' },
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'subtotal', label: 'Subtotal', type: 'currency', align: 'right' },
      { key: 'cgst', label: 'CGST', type: 'currency', align: 'right' },
      { key: 'sgst', label: 'SGST', type: 'currency', align: 'right' },
      { key: 'igst', label: 'IGST', type: 'currency', align: 'right' },
      { key: 'grandTotal', label: 'Grand Total', type: 'currency', align: 'right' },
      { key: 'paidAmount', label: 'Paid', type: 'currency', align: 'right' },
      { key: 'balanceDue', label: 'Balance', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
    ],
  },
  {
    slug: 'sales-by-customer',
    name: 'Sales by Customer',
    category: 'SALES',
    description: 'Aggregated sales per customer with outstanding balance',
    permission: 'INVOICE_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'branchId', label: 'Branch', type: 'select', required: false },
    ],
    columns: [
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'phone', label: 'Phone', type: 'string' },
      { key: 'invoiceCount', label: 'Invoices', type: 'number', align: 'right' },
      { key: 'totalSales', label: 'Total Sales', type: 'currency', align: 'right' },
      { key: 'totalPaid', label: 'Total Paid', type: 'currency', align: 'right' },
      { key: 'outstanding', label: 'Outstanding', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'sales-by-item',
    name: 'Sales by Item',
    category: 'SALES',
    description: 'Item-wise sales quantity and revenue',
    permission: 'INVOICE_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'categoryId', label: 'Category', type: 'select', required: false },
      { key: 'branchId', label: 'Branch', type: 'select', required: false },
    ],
    columns: [
      { key: 'itemCode', label: 'Item Code', type: 'string' },
      { key: 'itemName', label: 'Item Name', type: 'string' },
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'quantitySold', label: 'Qty Sold', type: 'number', align: 'right' },
      { key: 'unit', label: 'Unit', type: 'string' },
      { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
      { key: 'cogs', label: 'COGS', type: 'currency', align: 'right' },
      { key: 'grossProfit', label: 'Gross Profit', type: 'currency', align: 'right' },
      { key: 'grossMargin', label: 'Margin %', type: 'percent', align: 'right' },
    ],
  },
  {
    slug: 'sales-by-category',
    name: 'Sales by Category',
    category: 'SALES',
    description: 'Revenue grouped by product category',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'invoiceCount', label: 'Invoices', type: 'number', align: 'right' },
      { key: 'quantitySold', label: 'Qty Sold', type: 'number', align: 'right' },
      { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
      { key: 'revenueShare', label: 'Share %', type: 'percent', align: 'right' },
    ],
  },
  {
    slug: 'sales-by-salesperson',
    name: 'Sales by Salesperson',
    category: 'SALES',
    description: 'Sales performance per user/salesperson',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'salesperson', label: 'Salesperson', type: 'string' },
      { key: 'invoiceCount', label: 'Invoices', type: 'number', align: 'right' },
      { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
      { key: 'avgInvoiceValue', label: 'Avg Invoice', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'outstanding-receivables',
    name: 'Outstanding Receivables',
    category: 'SALES',
    description: 'Unpaid invoices ageing analysis (30/60/90/90+ days)',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'asOfDate', label: 'As of Date', type: 'date', required: true },
      { key: 'customerId', label: 'Customer', type: 'select', required: false },
    ],
    columns: [
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'invoiceNumber', label: 'Invoice No', type: 'string' },
      { key: 'invoiceDate', label: 'Invoice Date', type: 'date' },
      { key: 'dueDate', label: 'Due Date', type: 'date' },
      { key: 'grandTotal', label: 'Total', type: 'currency', align: 'right' },
      { key: 'paidAmount', label: 'Paid', type: 'currency', align: 'right' },
      { key: 'balanceDue', label: 'Balance', type: 'currency', align: 'right' },
      { key: 'daysBucket', label: 'Ageing', type: 'string' },
    ],
  },
  {
    slug: 'customer-ledger',
    name: 'Customer Ledger',
    category: 'SALES',
    description: 'Full transaction history for a customer (invoices + payments + credit notes)',
    permission: 'INVOICE_VIEW',
    supportsAsync: true,
    params: [
      { key: 'customerId', label: 'Customer', type: 'select', required: true },
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'type', label: 'Type', type: 'string' },
      { key: 'reference', label: 'Reference', type: 'string' },
      { key: 'debit', label: 'Debit', type: 'currency', align: 'right' },
      { key: 'credit', label: 'Credit', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Balance', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'payment-collection-report',
    name: 'Payment Collection Report',
    category: 'SALES',
    description: 'All collections by mode (cash/card/UPI/cheque)',
    permission: 'PAYMENT_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'mode', label: 'Payment Mode', type: 'select', required: false, options: [{ value: 'CASH', label: 'Cash' }, { value: 'CARD', label: 'Card' }, { value: 'UPI', label: 'UPI' }, { value: 'CHEQUE', label: 'Cheque' }, { value: 'NEFT', label: 'NEFT' }] },
    ],
    columns: [
      { key: 'paymentDate', label: 'Date', type: 'date' },
      { key: 'receiptNumber', label: 'Receipt No', type: 'string' },
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'mode', label: 'Mode', type: 'string' },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
      { key: 'reference', label: 'Reference', type: 'string' },
    ],
  },
  {
    slug: 'credit-note-report',
    name: 'Credit Note Report',
    category: 'SALES',
    description: 'All credit notes issued in the period',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'creditNoteNumber', label: 'CN No', type: 'string' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'reason', label: 'Reason', type: 'string' },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
    ],
  },
  {
    slug: 'sales-return-report',
    name: 'Sales Return Report',
    category: 'SALES',
    description: 'All sales returns with item details',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'returnNumber', label: 'Return No', type: 'string' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'originalInvoice', label: 'Invoice No', type: 'string' },
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'returnAmount', label: 'Return Amount', type: 'currency', align: 'right' },
      { key: 'reason', label: 'Reason', type: 'string' },
    ],
  },
  {
    slug: 'delivery-challan-report',
    name: 'Delivery Challan Report',
    category: 'SALES',
    description: 'All delivery challans and their conversion status',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'challanNumber', label: 'Challan No', type: 'string' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'totalQty', label: 'Qty', type: 'number', align: 'right' },
      { key: 'totalValue', label: 'Value', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
      { key: 'convertedInvoice', label: 'Invoice', type: 'string' },
    ],
  },
  {
    slug: 'quotation-conversion-report',
    name: 'Quotation Conversion Report',
    category: 'SALES',
    description: 'Quotations and their conversion to invoices',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'quotationNumber', label: 'Quotation No', type: 'string' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'totalValue', label: 'Value', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
      { key: 'convertedInvoice', label: 'Invoice', type: 'string' },
      { key: 'convertedDate', label: 'Converted Date', type: 'date' },
    ],
  },
  {
    slug: 'pos-summary-report',
    name: 'POS Summary Report',
    category: 'SALES',
    description: 'Point-of-sale daily summary by shift/user',
    permission: 'POS_MANAGE',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'branchId', label: 'Branch', type: 'select', required: false },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'cashier', label: 'Cashier', type: 'string' },
      { key: 'totalTransactions', label: 'Transactions', type: 'number', align: 'right' },
      { key: 'cashSales', label: 'Cash', type: 'currency', align: 'right' },
      { key: 'cardSales', label: 'Card', type: 'currency', align: 'right' },
      { key: 'upiSales', label: 'UPI', type: 'currency', align: 'right' },
      { key: 'totalSales', label: 'Total', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'top-selling-items',
    name: 'Top Selling Items',
    category: 'SALES',
    description: 'Top N items by revenue or quantity',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'limit', label: 'Top N', type: 'number', required: false, default: '20' },
      { key: 'sortBy', label: 'Sort By', type: 'select', required: false, options: [{ value: 'revenue', label: 'Revenue' }, { value: 'quantity', label: 'Quantity' }] },
    ],
    columns: [
      { key: 'rank', label: '#', type: 'number', align: 'right' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'quantitySold', label: 'Qty Sold', type: 'number', align: 'right' },
      { key: 'revenue', label: 'Revenue', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'slow-moving-items',
    name: 'Slow Moving Items',
    category: 'SALES',
    description: 'Items with no or low sales in the period',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'maxSalesQty', label: 'Max Qty Threshold', type: 'number', required: false, default: '5' },
    ],
    columns: [
      { key: 'itemCode', label: 'Item Code', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'currentStock', label: 'Stock', type: 'number', align: 'right' },
      { key: 'quantitySold', label: 'Qty Sold', type: 'number', align: 'right' },
      { key: 'lastSaleDate', label: 'Last Sale', type: 'date' },
    ],
  },
  {
    slug: 'customer-statement',
    name: 'Customer Statement',
    category: 'SALES',
    description: 'Formal statement of account for a customer',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'customerId', label: 'Customer', type: 'select', required: true },
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'description', label: 'Description', type: 'string' },
      { key: 'debit', label: 'Debit', type: 'currency', align: 'right' },
      { key: 'credit', label: 'Credit', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Balance', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'loyalty-points-report',
    name: 'Loyalty Points Report',
    category: 'SALES',
    description: 'Customer loyalty points earned, redeemed and balance',
    permission: 'CRM_LOYALTY_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'phone', label: 'Phone', type: 'string' },
      { key: 'openingPoints', label: 'Opening', type: 'number', align: 'right' },
      { key: 'earned', label: 'Earned', type: 'number', align: 'right' },
      { key: 'redeemed', label: 'Redeemed', type: 'number', align: 'right' },
      { key: 'closingPoints', label: 'Closing', type: 'number', align: 'right' },
    ],
  },
  {
    slug: 'discount-report',
    name: 'Discount Report',
    category: 'SALES',
    description: 'Discounts given per invoice and per item',
    permission: 'INVOICE_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'invoiceNumber', label: 'Invoice No', type: 'string' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'grossAmount', label: 'Gross', type: 'currency', align: 'right' },
      { key: 'discountAmount', label: 'Discount', type: 'currency', align: 'right' },
      { key: 'discountPercent', label: 'Disc %', type: 'percent', align: 'right' },
      { key: 'netAmount', label: 'Net', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'sales-target-vs-actual',
    name: 'Sales Target vs Actual',
    category: 'SALES',
    description: 'Branch-wise sales target achievement',
    permission: 'INVOICE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'branch', label: 'Branch', type: 'string' },
      { key: 'target', label: 'Target', type: 'currency', align: 'right' },
      { key: 'actual', label: 'Actual', type: 'currency', align: 'right' },
      { key: 'achievement', label: 'Achievement %', type: 'percent', align: 'right' },
      { key: 'variance', label: 'Variance', type: 'currency', align: 'right' },
    ],
  },

  // ── PURCHASE REPORTS ──
  {
    slug: 'purchase-register',
    name: 'Purchase Register',
    category: 'PURCHASE',
    description: 'All purchase bills/GRNs with supplier and GST details',
    permission: 'GRN_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'supplierId', label: 'Supplier', type: 'select', required: false },
    ],
    columns: [
      { key: 'grnNumber', label: 'GRN No', type: 'string' },
      { key: 'grnDate', label: 'Date', type: 'date' },
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'supplierInvoice', label: 'Supplier Invoice', type: 'string' },
      { key: 'subtotal', label: 'Subtotal', type: 'currency', align: 'right' },
      { key: 'cgst', label: 'CGST', type: 'currency', align: 'right' },
      { key: 'sgst', label: 'SGST', type: 'currency', align: 'right' },
      { key: 'igst', label: 'IGST', type: 'currency', align: 'right' },
      { key: 'grandTotal', label: 'Total', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
    ],
  },
  {
    slug: 'purchase-by-supplier',
    name: 'Purchase by Supplier',
    category: 'PURCHASE',
    description: 'Aggregated purchases per supplier',
    permission: 'GRN_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'grnCount', label: 'GRNs', type: 'number', align: 'right' },
      { key: 'totalPurchase', label: 'Total Purchase', type: 'currency', align: 'right' },
      { key: 'totalPaid', label: 'Paid', type: 'currency', align: 'right' },
      { key: 'outstanding', label: 'Outstanding', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'purchase-by-item',
    name: 'Purchase by Item',
    category: 'PURCHASE',
    description: 'Item-wise purchase quantity and cost',
    permission: 'GRN_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'itemCode', label: 'Item Code', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'quantityReceived', label: 'Qty Received', type: 'number', align: 'right' },
      { key: 'totalCost', label: 'Total Cost', type: 'currency', align: 'right' },
      { key: 'avgCost', label: 'Avg Cost', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'outstanding-payables',
    name: 'Outstanding Payables',
    category: 'PURCHASE',
    description: 'Unpaid supplier bills ageing analysis',
    permission: 'GRN_VIEW',
    supportsAsync: false,
    params: [
      { key: 'asOfDate', label: 'As of Date', type: 'date', required: true },
      { key: 'supplierId', label: 'Supplier', type: 'select', required: false },
    ],
    columns: [
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'grnNumber', label: 'GRN No', type: 'string' },
      { key: 'grnDate', label: 'GRN Date', type: 'date' },
      { key: 'dueDate', label: 'Due Date', type: 'date' },
      { key: 'totalAmount', label: 'Total', type: 'currency', align: 'right' },
      { key: 'paidAmount', label: 'Paid', type: 'currency', align: 'right' },
      { key: 'balanceDue', label: 'Balance', type: 'currency', align: 'right' },
      { key: 'daysBucket', label: 'Ageing', type: 'string' },
    ],
  },
  {
    slug: 'supplier-ledger',
    name: 'Supplier Ledger',
    category: 'PURCHASE',
    description: 'Full transaction history for a supplier',
    permission: 'GRN_VIEW',
    supportsAsync: true,
    params: [
      { key: 'supplierId', label: 'Supplier', type: 'select', required: true },
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'type', label: 'Type', type: 'string' },
      { key: 'reference', label: 'Reference', type: 'string' },
      { key: 'debit', label: 'Debit', type: 'currency', align: 'right' },
      { key: 'credit', label: 'Credit', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Balance', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'purchase-order-status',
    name: 'Purchase Order Status',
    category: 'PURCHASE',
    description: 'PO fulfilment status and pending GRNs',
    permission: 'PO_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'status', label: 'Status', type: 'select', required: false, options: [{ value: 'OPEN', label: 'Open' }, { value: 'PARTIAL', label: 'Partial' }, { value: 'FULFILLED', label: 'Fulfilled' }, { value: 'CANCELLED', label: 'Cancelled' }] },
    ],
    columns: [
      { key: 'poNumber', label: 'PO No', type: 'string' },
      { key: 'poDate', label: 'PO Date', type: 'date' },
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'orderedQty', label: 'Ordered Qty', type: 'number', align: 'right' },
      { key: 'receivedQty', label: 'Received Qty', type: 'number', align: 'right' },
      { key: 'pendingQty', label: 'Pending Qty', type: 'number', align: 'right' },
      { key: 'totalValue', label: 'Value', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
    ],
  },
  {
    slug: 'purchase-return-report',
    name: 'Purchase Return Report',
    category: 'PURCHASE',
    description: 'All purchase returns with debit note details',
    permission: 'PURCHASE_RETURN_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'returnNumber', label: 'Return No', type: 'string' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'originalGrn', label: 'GRN No', type: 'string' },
      { key: 'returnAmount', label: 'Amount', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
    ],
  },
  {
    slug: 'grn-report',
    name: 'GRN Report',
    category: 'PURCHASE',
    description: 'Goods Receipt Note details',
    permission: 'GRN_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'supplierId', label: 'Supplier', type: 'select', required: false },
    ],
    columns: [
      { key: 'grnNumber', label: 'GRN No', type: 'string' },
      { key: 'grnDate', label: 'Date', type: 'date' },
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'warehouseName', label: 'Warehouse', type: 'string' },
      { key: 'itemCount', label: 'Items', type: 'number', align: 'right' },
      { key: 'totalQty', label: 'Total Qty', type: 'number', align: 'right' },
      { key: 'totalValue', label: 'Total Value', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
    ],
  },
  {
    slug: 'expense-report',
    name: 'Expense Report',
    category: 'PURCHASE',
    description: 'Business expenses by category and vendor',
    permission: 'EXPENSE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'expenseNumber', label: 'Expense No', type: 'string' },
      { key: 'vendor', label: 'Vendor', type: 'string' },
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'description', label: 'Description', type: 'string' },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
      { key: 'gst', label: 'GST', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'landed-cost-report',
    name: 'Landed Cost Report',
    category: 'PURCHASE',
    description: 'Landed costs allocated to GRNs',
    permission: 'GRN_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'grnNumber', label: 'GRN No', type: 'string' },
      { key: 'grnDate', label: 'Date', type: 'date' },
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'costType', label: 'Cost Type', type: 'string' },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
      { key: 'allocationMethod', label: 'Method', type: 'string' },
    ],
  },
  {
    slug: 'supplier-payment-report',
    name: 'Supplier Payment Report',
    category: 'PURCHASE',
    description: 'All payments made to suppliers',
    permission: 'PAYMENT_OUT_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'supplierId', label: 'Supplier', type: 'select', required: false },
    ],
    columns: [
      { key: 'paymentDate', label: 'Date', type: 'date' },
      { key: 'paymentNumber', label: 'Payment No', type: 'string' },
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'mode', label: 'Mode', type: 'string' },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
      { key: 'reference', label: 'Reference', type: 'string' },
    ],
  },
  {
    slug: 'price-trend',
    name: 'Price Trend Report',
    category: 'PURCHASE',
    description: 'Price trend for items across purchase orders',
    permission: 'GRN_VIEW',
    supportsAsync: false,
    params: [
      { key: 'itemId', label: 'Item', type: 'select', required: true },
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'grnNumber', label: 'GRN No', type: 'string' },
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'quantity', label: 'Qty', type: 'number', align: 'right' },
      { key: 'unitCost', label: 'Unit Cost', type: 'currency', align: 'right' },
    ],
  },

  // ── INVENTORY REPORTS ──
  {
    slug: 'stock-summary',
    name: 'Stock Summary',
    category: 'INVENTORY',
    description: 'Current stock levels across all items and warehouses',
    permission: 'STOCK_VIEW',
    supportsAsync: true,
    params: [
      { key: 'warehouseId', label: 'Warehouse', type: 'select', required: false },
      { key: 'categoryId', label: 'Category', type: 'select', required: false },
    ],
    columns: [
      { key: 'itemCode', label: 'Item Code', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'warehouse', label: 'Warehouse', type: 'string' },
      { key: 'quantityOnHand', label: 'Qty on Hand', type: 'number', align: 'right' },
      { key: 'reorderLevel', label: 'Reorder Level', type: 'number', align: 'right' },
      { key: 'valuationCost', label: 'FIFO Cost', type: 'currency', align: 'right' },
      { key: 'totalValue', label: 'Total Value', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'stock-movement',
    name: 'Stock Movement Report',
    category: 'INVENTORY',
    description: 'Opening stock, receipts, issues, and closing stock per item',
    permission: 'STOCK_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'itemId', label: 'Item', type: 'select', required: false },
      { key: 'warehouseId', label: 'Warehouse', type: 'select', required: false },
    ],
    columns: [
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'warehouse', label: 'Warehouse', type: 'string' },
      { key: 'openingQty', label: 'Opening', type: 'number', align: 'right' },
      { key: 'receivedQty', label: 'Received', type: 'number', align: 'right' },
      { key: 'issuedQty', label: 'Issued', type: 'number', align: 'right' },
      { key: 'adjustedQty', label: 'Adjusted', type: 'number', align: 'right' },
      { key: 'closingQty', label: 'Closing', type: 'number', align: 'right' },
    ],
  },
  {
    slug: 'inventory-valuation',
    name: 'Inventory Valuation (FIFO)',
    category: 'INVENTORY',
    description: 'Inventory value using FIFO costing method',
    permission: 'STOCK_VIEW',
    supportsAsync: true,
    params: [
      { key: 'asOfDate', label: 'As of Date', type: 'date', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'select', required: false },
    ],
    columns: [
      { key: 'itemCode', label: 'Item Code', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'quantityOnHand', label: 'Qty', type: 'number', align: 'right' },
      { key: 'fifoUnitCost', label: 'FIFO Cost', type: 'currency', align: 'right' },
      { key: 'totalValue', label: 'Total Value', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'reorder-report',
    name: 'Reorder Report',
    category: 'INVENTORY',
    description: 'Items below reorder level that need replenishment',
    permission: 'REORDER_VIEW',
    supportsAsync: false,
    params: [
      { key: 'warehouseId', label: 'Warehouse', type: 'select', required: false },
    ],
    columns: [
      { key: 'itemCode', label: 'Item Code', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'warehouse', label: 'Warehouse', type: 'string' },
      { key: 'currentStock', label: 'Current Stock', type: 'number', align: 'right' },
      { key: 'reorderLevel', label: 'Reorder Level', type: 'number', align: 'right' },
      { key: 'reorderQty', label: 'Reorder Qty', type: 'number', align: 'right' },
      { key: 'preferredSupplier', label: 'Supplier', type: 'string' },
    ],
  },
  {
    slug: 'stock-ageing',
    name: 'Stock Ageing Report',
    category: 'INVENTORY',
    description: 'Stock age analysis (30/60/90/90+ days old)',
    permission: 'STOCK_VIEW',
    supportsAsync: true,
    params: [
      { key: 'asOfDate', label: 'As of Date', type: 'date', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'select', required: false },
    ],
    columns: [
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'qty0to30', label: '0-30 Days', type: 'number', align: 'right' },
      { key: 'qty31to60', label: '31-60 Days', type: 'number', align: 'right' },
      { key: 'qty61to90', label: '61-90 Days', type: 'number', align: 'right' },
      { key: 'qty90plus', label: '90+ Days', type: 'number', align: 'right' },
      { key: 'totalQty', label: 'Total', type: 'number', align: 'right' },
      { key: 'totalValue', label: 'Value', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'physical-verification-report',
    name: 'Physical Verification Report',
    category: 'INVENTORY',
    description: 'Variance between book stock and physical count',
    permission: 'PHYSICAL_VERIFICATION_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'verificationNumber', label: 'PV No', type: 'string' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'warehouseName', label: 'Warehouse', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'bookQty', label: 'Book Qty', type: 'number', align: 'right' },
      { key: 'physicalQty', label: 'Physical Qty', type: 'number', align: 'right' },
      { key: 'variance', label: 'Variance', type: 'number', align: 'right' },
      { key: 'varianceValue', label: 'Variance Value', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'stock-transfer-report',
    name: 'Stock Transfer Report',
    category: 'INVENTORY',
    description: 'Inter-warehouse stock transfers',
    permission: 'STOCK_TRANSFER_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'transferNumber', label: 'Transfer No', type: 'string' },
      { key: 'transferDate', label: 'Date', type: 'date' },
      { key: 'fromWarehouse', label: 'From', type: 'string' },
      { key: 'toWarehouse', label: 'To', type: 'string' },
      { key: 'itemCount', label: 'Items', type: 'number', align: 'right' },
      { key: 'totalQty', label: 'Qty', type: 'number', align: 'right' },
      { key: 'totalValue', label: 'Value', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
    ],
  },
  {
    slug: 'fabric-roll-report',
    name: 'Fabric Roll Report',
    category: 'INVENTORY',
    description: 'Fabric roll tracking with roll-wise metres',
    permission: 'FABRIC_ROLL_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'select', required: false },
    ],
    columns: [
      { key: 'rollNumber', label: 'Roll No', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'colour', label: 'Colour', type: 'string' },
      { key: 'totalMetres', label: 'Total Metres', type: 'number', align: 'right' },
      { key: 'usedMetres', label: 'Used Metres', type: 'number', align: 'right' },
      { key: 'remainingMetres', label: 'Remaining', type: 'number', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
    ],
  },
  {
    slug: 'warehouse-wise-stock',
    name: 'Warehouse-wise Stock',
    category: 'INVENTORY',
    description: 'Stock levels broken down by warehouse',
    permission: 'STOCK_VIEW',
    supportsAsync: true,
    params: [
      { key: 'warehouseId', label: 'Warehouse', type: 'select', required: false },
      { key: 'categoryId', label: 'Category', type: 'select', required: false },
    ],
    columns: [
      { key: 'warehouse', label: 'Warehouse', type: 'string' },
      { key: 'itemCode', label: 'Item Code', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'quantityOnHand', label: 'Qty', type: 'number', align: 'right' },
      { key: 'totalValue', label: 'Value', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'stock-ledger',
    name: 'Stock Ledger',
    category: 'INVENTORY',
    description: 'Full stock movement ledger for an item',
    permission: 'STOCK_VIEW',
    supportsAsync: true,
    params: [
      { key: 'itemId', label: 'Item', type: 'select', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'select', required: false },
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'transactionType', label: 'Type', type: 'string' },
      { key: 'reference', label: 'Reference', type: 'string' },
      { key: 'inQty', label: 'In Qty', type: 'number', align: 'right' },
      { key: 'outQty', label: 'Out Qty', type: 'number', align: 'right' },
      { key: 'balance', label: 'Balance', type: 'number', align: 'right' },
      { key: 'unitCost', label: 'Unit Cost', type: 'currency', align: 'right' },
      { key: 'totalValue', label: 'Total Value', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'dead-stock-report',
    name: 'Dead Stock Report',
    category: 'INVENTORY',
    description: 'Items with no movement for over 180 days',
    permission: 'STOCK_VIEW',
    supportsAsync: false,
    params: [
      { key: 'asOfDate', label: 'As of Date', type: 'date', required: true },
      { key: 'daysSinceMovement', label: 'Days Since Movement', type: 'number', required: false, default: '180' },
    ],
    columns: [
      { key: 'itemCode', label: 'Item Code', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'currentStock', label: 'Stock', type: 'number', align: 'right' },
      { key: 'lastMovementDate', label: 'Last Movement', type: 'date' },
      { key: 'daysIdle', label: 'Days Idle', type: 'number', align: 'right' },
      { key: 'stockValue', label: 'Stock Value', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'adjustment-report',
    name: 'Stock Adjustment Report',
    category: 'INVENTORY',
    description: 'All stock adjustments with reasons',
    permission: 'STOCK_ADJUSTMENT_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'adjustmentNumber', label: 'Adj No', type: 'string' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'warehouse', label: 'Warehouse', type: 'string' },
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'adjustmentType', label: 'Type', type: 'string' },
      { key: 'quantity', label: 'Qty', type: 'number', align: 'right' },
      { key: 'reason', label: 'Reason', type: 'string' },
      { key: 'valueImpact', label: 'Value Impact', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'reservation-report',
    name: 'Stock Reservation Report',
    category: 'INVENTORY',
    description: 'Stock reserved against sales orders/quotations',
    permission: 'STOCK_VIEW',
    supportsAsync: false,
    params: [
      { key: 'asOfDate', label: 'As of Date', type: 'date', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'select', required: false },
    ],
    columns: [
      { key: 'itemName', label: 'Item', type: 'string' },
      { key: 'warehouse', label: 'Warehouse', type: 'string' },
      { key: 'reservedQty', label: 'Reserved Qty', type: 'number', align: 'right' },
      { key: 'availableQty', label: 'Available Qty', type: 'number', align: 'right' },
      { key: 'totalQty', label: 'Total Qty', type: 'number', align: 'right' },
      { key: 'reservedFor', label: 'Reserved For', type: 'string' },
    ],
  },

  // ── FINANCIAL REPORTS ──
  {
    slug: 'day-book',
    name: 'Day Book',
    category: 'FINANCIAL',
    description: 'All financial transactions for a day',
    permission: 'JOURNAL_VIEW',
    supportsAsync: false,
    params: [
      { key: 'date', label: 'Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'time', label: 'Time', type: 'string' },
      { key: 'type', label: 'Type', type: 'string' },
      { key: 'reference', label: 'Reference', type: 'string' },
      { key: 'description', label: 'Description', type: 'string' },
      { key: 'debit', label: 'Debit', type: 'currency', align: 'right' },
      { key: 'credit', label: 'Credit', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'account-ledger',
    name: 'Account Ledger',
    category: 'FINANCIAL',
    description: 'Detailed ledger for a specific account',
    permission: 'LEDGER_VIEW',
    supportsAsync: true,
    params: [
      { key: 'accountId', label: 'Account', type: 'select', required: true },
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'journalNumber', label: 'Journal No', type: 'string' },
      { key: 'description', label: 'Description', type: 'string' },
      { key: 'debit', label: 'Debit', type: 'currency', align: 'right' },
      { key: 'credit', label: 'Credit', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Balance', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'trial-balance-report',
    name: 'Trial Balance',
    category: 'FINANCIAL',
    description: 'Trial balance with opening, movement and closing for each account',
    permission: 'TRIAL_BALANCE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'accountCode', label: 'Code', type: 'string' },
      { key: 'accountName', label: 'Account', type: 'string' },
      { key: 'openingDebit', label: 'Opening Dr', type: 'currency', align: 'right' },
      { key: 'openingCredit', label: 'Opening Cr', type: 'currency', align: 'right' },
      { key: 'periodDebit', label: 'Period Dr', type: 'currency', align: 'right' },
      { key: 'periodCredit', label: 'Period Cr', type: 'currency', align: 'right' },
      { key: 'closingDebit', label: 'Closing Dr', type: 'currency', align: 'right' },
      { key: 'closingCredit', label: 'Closing Cr', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'profit-loss-report',
    name: 'Profit & Loss Statement',
    category: 'FINANCIAL',
    description: 'Income and expense summary for the period',
    permission: 'PROFIT_LOSS_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'accountName', label: 'Account', type: 'string' },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'balance-sheet-report',
    name: 'Balance Sheet',
    category: 'FINANCIAL',
    description: 'Assets, liabilities and equity as of date',
    permission: 'BALANCE_SHEET_VIEW',
    supportsAsync: false,
    params: [
      { key: 'asOfDate', label: 'As of Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'section', label: 'Section', type: 'string' },
      { key: 'accountName', label: 'Account', type: 'string' },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'cash-flow-report',
    name: 'Cash Flow Statement',
    category: 'FINANCIAL',
    description: 'Operating, investing and financing cash flows',
    permission: 'CASH_FLOW_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'section', label: 'Section', type: 'string' },
      { key: 'description', label: 'Description', type: 'string' },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'expense-analysis',
    name: 'Expense Analysis',
    category: 'FINANCIAL',
    description: 'Expense breakdown by category',
    permission: 'JOURNAL_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'category', label: 'Category', type: 'string' },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right' },
      { key: 'share', label: 'Share %', type: 'percent', align: 'right' },
    ],
  },
  {
    slug: 'bank-book',
    name: 'Bank Book',
    category: 'FINANCIAL',
    description: 'Bank account statement with running balance',
    permission: 'BANK_RECONCILIATION_VIEW',
    supportsAsync: true,
    params: [
      { key: 'bankAccountId', label: 'Bank Account', type: 'select', required: true },
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'description', label: 'Description', type: 'string' },
      { key: 'reference', label: 'Reference', type: 'string' },
      { key: 'debit', label: 'Debit', type: 'currency', align: 'right' },
      { key: 'credit', label: 'Credit', type: 'currency', align: 'right' },
      { key: 'balance', label: 'Balance', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'tds-report',
    name: 'TDS Report',
    category: 'FINANCIAL',
    description: 'TDS deducted and payable summary',
    permission: 'TDS_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'deducteeType', label: 'Deductee Type', type: 'string' },
      { key: 'panNumber', label: 'PAN', type: 'string' },
      { key: 'section', label: 'Section', type: 'string' },
      { key: 'grossAmount', label: 'Gross Amount', type: 'currency', align: 'right' },
      { key: 'tdsRate', label: 'TDS Rate', type: 'percent', align: 'right' },
      { key: 'tdsAmount', label: 'TDS Amount', type: 'currency', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
    ],
  },
  {
    slug: 'depreciation-schedule',
    name: 'Depreciation Schedule',
    category: 'FINANCIAL',
    description: 'Fixed asset depreciation schedule',
    permission: 'FIXED_ASSET_VIEW',
    supportsAsync: false,
    params: [
      { key: 'financialYear', label: 'Financial Year', type: 'text', required: true },
    ],
    columns: [
      { key: 'assetName', label: 'Asset', type: 'string' },
      { key: 'assetCategory', label: 'Category', type: 'string' },
      { key: 'purchaseDate', label: 'Purchase Date', type: 'date' },
      { key: 'openingValue', label: 'Opening Value', type: 'currency', align: 'right' },
      { key: 'additions', label: 'Additions', type: 'currency', align: 'right' },
      { key: 'depreciation', label: 'Depreciation', type: 'currency', align: 'right' },
      { key: 'closingValue', label: 'Net Book Value', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'journal-report',
    name: 'Journal Report',
    category: 'FINANCIAL',
    description: 'All journal entries in the period',
    permission: 'JOURNAL_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'journalDate', label: 'Date', type: 'date' },
      { key: 'journalNumber', label: 'Journal No', type: 'string' },
      { key: 'description', label: 'Description', type: 'string' },
      { key: 'totalDebit', label: 'Total Debit', type: 'currency', align: 'right' },
      { key: 'totalCredit', label: 'Total Credit', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'profit-center-report',
    name: 'Profit Center / Branch P&L',
    category: 'FINANCIAL',
    description: 'Revenue and expenses per branch/profit center',
    permission: 'PROFIT_LOSS_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'branch', label: 'Branch', type: 'string' },
      { key: 'totalSales', label: 'Sales', type: 'currency', align: 'right' },
      { key: 'cogs', label: 'COGS', type: 'currency', align: 'right' },
      { key: 'grossProfit', label: 'Gross Profit', type: 'currency', align: 'right' },
      { key: 'expenses', label: 'Expenses', type: 'currency', align: 'right' },
      { key: 'netProfit', label: 'Net Profit', type: 'currency', align: 'right' },
      { key: 'margin', label: 'Margin %', type: 'percent', align: 'right' },
    ],
  },
  {
    slug: 'fund-flow',
    name: 'Fund Flow Statement',
    category: 'FINANCIAL',
    description: 'Sources and uses of funds in the period',
    permission: 'CASH_FLOW_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'section', label: 'Section', type: 'string' },
      { key: 'description', label: 'Description', type: 'string' },
      { key: 'sourceOfFund', label: 'Source', type: 'currency', align: 'right' },
      { key: 'useOfFund', label: 'Use', type: 'currency', align: 'right' },
    ],
  },

  // ── HR REPORTS ──
  {
    slug: 'payroll-report',
    name: 'Payroll Report',
    category: 'HR',
    description: 'Employee payroll details for the month',
    permission: 'PAYROLL_VIEW',
    supportsAsync: true,
    params: [
      { key: 'month', label: 'Month (YYYY-MM)', type: 'text', required: true },
    ],
    columns: [
      { key: 'employeeCode', label: 'Emp Code', type: 'string' },
      { key: 'employeeName', label: 'Employee', type: 'string' },
      { key: 'department', label: 'Department', type: 'string' },
      { key: 'basicSalary', label: 'Basic', type: 'currency', align: 'right' },
      { key: 'allowances', label: 'Allowances', type: 'currency', align: 'right' },
      { key: 'grossSalary', label: 'Gross', type: 'currency', align: 'right' },
      { key: 'deductions', label: 'Deductions', type: 'currency', align: 'right' },
      { key: 'netSalary', label: 'Net Pay', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'attendance-report',
    name: 'Attendance Report',
    category: 'HR',
    description: 'Employee attendance summary for the month',
    permission: 'ATTENDANCE_REPORT',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'employeeId', label: 'Employee', type: 'select', required: false },
    ],
    columns: [
      { key: 'employeeCode', label: 'Emp Code', type: 'string' },
      { key: 'employeeName', label: 'Employee', type: 'string' },
      { key: 'presentDays', label: 'Present', type: 'number', align: 'right' },
      { key: 'absentDays', label: 'Absent', type: 'number', align: 'right' },
      { key: 'halfDays', label: 'Half Day', type: 'number', align: 'right' },
      { key: 'leaveDays', label: 'Leave', type: 'number', align: 'right' },
      { key: 'overtimeHours', label: 'OT Hours', type: 'number', align: 'right' },
    ],
  },
  {
    slug: 'leave-report',
    name: 'Leave Report',
    category: 'HR',
    description: 'Leave applications and balances by employee',
    permission: 'LEAVE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'employeeName', label: 'Employee', type: 'string' },
      { key: 'leaveType', label: 'Leave Type', type: 'string' },
      { key: 'fromDate', label: 'From', type: 'date' },
      { key: 'toDate', label: 'To', type: 'date' },
      { key: 'days', label: 'Days', type: 'number', align: 'right' },
      { key: 'status', label: 'Status', type: 'string' },
      { key: 'reason', label: 'Reason', type: 'string' },
    ],
  },
  {
    slug: 'employee-master-report',
    name: 'Employee Master Report',
    category: 'HR',
    description: 'Full employee directory with key details',
    permission: 'EMPLOYEE_VIEW',
    supportsAsync: false,
    params: [
      { key: 'status', label: 'Status', type: 'select', required: false, options: [{ value: 'ACTIVE', label: 'Active' }, { value: 'INACTIVE', label: 'Inactive' }] },
    ],
    columns: [
      { key: 'employeeCode', label: 'Emp Code', type: 'string' },
      { key: 'employeeName', label: 'Name', type: 'string' },
      { key: 'department', label: 'Department', type: 'string' },
      { key: 'designation', label: 'Designation', type: 'string' },
      { key: 'dateOfJoining', label: 'DOJ', type: 'date' },
      { key: 'status', label: 'Status', type: 'string' },
      { key: 'contactNumber', label: 'Phone', type: 'string' },
    ],
  },
  {
    slug: 'alteration-report',
    name: 'Alteration Order Report',
    category: 'HR',
    description: 'Alteration orders by tailor with pending and completed counts',
    permission: 'ALTERATION_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'alterationNumber', label: 'Alteration No', type: 'string' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'tailorName', label: 'Tailor', type: 'string' },
      { key: 'totalPieces', label: 'Pieces', type: 'number', align: 'right' },
      { key: 'deliveryDate', label: 'Delivery Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'string' },
      { key: 'charges', label: 'Charges', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'tailor-work-log-report',
    name: 'Tailor Work Log Report',
    category: 'HR',
    description: 'Work units and earnings per tailor',
    permission: 'ALTERATION_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'employeeId', label: 'Tailor', type: 'select', required: false },
    ],
    columns: [
      { key: 'tailorName', label: 'Tailor', type: 'string' },
      { key: 'workUnits', label: 'Work Units', type: 'number', align: 'right' },
      { key: 'completedOrders', label: 'Completed Orders', type: 'number', align: 'right' },
      { key: 'totalEarnings', label: 'Earnings', type: 'currency', align: 'right' },
    ],
  },

  // ── AR / AP AGING REPORTS ──
  {
    slug: 'ar-aging',
    name: 'AR Aging Summary',
    category: 'FINANCIAL',
    description: 'Customer outstanding invoices bucketed by overdue days (0–30, 31–60, 61–90, 90+)',
    permission: 'REPORT_VIEW',
    supportsAsync: false,
    params: [
      { key: 'asOfDate', label: 'As of Date', type: 'date', required: false },
      { key: 'branchId', label: 'Branch', type: 'select', required: false },
    ],
    columns: [
      { key: 'customerName', label: 'Customer Name', type: 'string' },
      { key: 'days0to30', label: '0–30 Days (₹)', type: 'currency', align: 'right' },
      { key: 'days31to60', label: '31–60 Days (₹)', type: 'currency', align: 'right' },
      { key: 'days61to90', label: '61–90 Days (₹)', type: 'currency', align: 'right' },
      { key: 'days90plus', label: '90+ Days (₹)', type: 'currency', align: 'right' },
      { key: 'totalOutstanding', label: 'Total Outstanding (₹)', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'ap-aging',
    name: 'AP Aging Summary',
    category: 'FINANCIAL',
    description: 'Supplier outstanding payables bucketed by overdue days (0–30, 31–60, 61–90, 90+)',
    permission: 'REPORT_VIEW',
    supportsAsync: false,
    params: [
      { key: 'asOfDate', label: 'As of Date', type: 'date', required: false },
      { key: 'supplierId', label: 'Supplier', type: 'select', required: false },
    ],
    columns: [
      { key: 'supplierName', label: 'Supplier Name', type: 'string' },
      { key: 'days0to30', label: '0–30 Days (₹)', type: 'currency', align: 'right' },
      { key: 'days31to60', label: '31–60 Days (₹)', type: 'currency', align: 'right' },
      { key: 'days61to90', label: '61–90 Days (₹)', type: 'currency', align: 'right' },
      { key: 'days90plus', label: '90+ Days (₹)', type: 'currency', align: 'right' },
      { key: 'totalOutstanding', label: 'Total Outstanding (₹)', type: 'currency', align: 'right' },
    ],
  },

  // ── GST REPORTS ──
  {
    slug: 'gst-register',
    name: 'GST Register',
    category: 'GST',
    description: 'All GST transactions (sales + purchase) for the period',
    permission: 'GST_VIEW',
    supportsAsync: true,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
      { key: 'type', label: 'Type', type: 'select', required: false, options: [{ value: 'SALES', label: 'Sales' }, { value: 'PURCHASE', label: 'Purchase' }] },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'documentType', label: 'Type', type: 'string' },
      { key: 'documentNumber', label: 'Document No', type: 'string' },
      { key: 'partyName', label: 'Party', type: 'string' },
      { key: 'gstin', label: 'GSTIN', type: 'string' },
      { key: 'taxableValue', label: 'Taxable Value', type: 'currency', align: 'right' },
      { key: 'cgst', label: 'CGST', type: 'currency', align: 'right' },
      { key: 'sgst', label: 'SGST', type: 'currency', align: 'right' },
      { key: 'igst', label: 'IGST', type: 'currency', align: 'right' },
      { key: 'totalGst', label: 'Total GST', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'gstr1-report',
    name: 'GSTR-1 Report',
    category: 'GST',
    description: 'Outward supply details for GSTR-1 filing',
    permission: 'GSTR1_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'invoiceDate', label: 'Date', type: 'date' },
      { key: 'invoiceNumber', label: 'Invoice No', type: 'string' },
      { key: 'customerGstin', label: 'GSTIN', type: 'string' },
      { key: 'customerName', label: 'Customer', type: 'string' },
      { key: 'taxableValue', label: 'Taxable Value', type: 'currency', align: 'right' },
      { key: 'gstRate', label: 'GST Rate', type: 'percent', align: 'right' },
      { key: 'cgst', label: 'CGST', type: 'currency', align: 'right' },
      { key: 'sgst', label: 'SGST', type: 'currency', align: 'right' },
      { key: 'igst', label: 'IGST', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'gstr3b-report',
    name: 'GSTR-3B Summary',
    category: 'GST',
    description: 'Summary for GSTR-3B filing',
    permission: 'GSTR3B_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'section', label: 'Section', type: 'string' },
      { key: 'description', label: 'Description', type: 'string' },
      { key: 'taxableValue', label: 'Taxable Value', type: 'currency', align: 'right' },
      { key: 'igst', label: 'IGST', type: 'currency', align: 'right' },
      { key: 'cgst', label: 'CGST', type: 'currency', align: 'right' },
      { key: 'sgst', label: 'SGST', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'itc-register',
    name: 'ITC Register',
    category: 'GST',
    description: 'Input Tax Credit register from purchases',
    permission: 'GST_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'grnDate', label: 'Date', type: 'date' },
      { key: 'grnNumber', label: 'GRN No', type: 'string' },
      { key: 'supplierName', label: 'Supplier', type: 'string' },
      { key: 'supplierGstin', label: 'GSTIN', type: 'string' },
      { key: 'taxableValue', label: 'Taxable Value', type: 'currency', align: 'right' },
      { key: 'igstCredit', label: 'IGST ITC', type: 'currency', align: 'right' },
      { key: 'cgstCredit', label: 'CGST ITC', type: 'currency', align: 'right' },
      { key: 'sgstCredit', label: 'SGST ITC', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'gst-payable-report',
    name: 'GST Payable Report',
    category: 'GST',
    description: 'Net GST payable after ITC set-off',
    permission: 'GST_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'gstType', label: 'GST Type', type: 'string' },
      { key: 'outputTax', label: 'Output Tax', type: 'currency', align: 'right' },
      { key: 'itcAvailable', label: 'ITC', type: 'currency', align: 'right' },
      { key: 'netPayable', label: 'Net Payable', type: 'currency', align: 'right' },
    ],
  },
  {
    slug: 'reverse-charge-report',
    name: 'Reverse Charge Report',
    category: 'GST',
    description: 'Transactions attracting reverse charge mechanism',
    permission: 'GST_VIEW',
    supportsAsync: false,
    params: [
      { key: 'fromDate', label: 'From Date', type: 'date', required: true },
      { key: 'toDate', label: 'To Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'documentNumber', label: 'Document No', type: 'string' },
      { key: 'partyName', label: 'Party', type: 'string' },
      { key: 'taxableValue', label: 'Taxable Value', type: 'currency', align: 'right' },
      { key: 'rcmTax', label: 'RCM Tax', type: 'currency', align: 'right' },
      { key: 'section', label: 'Section', type: 'string' },
    ],
  },
];

export function getReportDefinition(slug: string): ReportDefinition | undefined {
  return REPORT_REGISTRY.find((r) => r.slug === slug);
}

export function getReportsByCategory(category: ReportDefinition['category']): ReportDefinition[] {
  return REPORT_REGISTRY.filter((r) => r.category === category);
}
